/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.*;
import Vue.*;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignElement;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author azus
 */
public class AcceuilSecretaire extends javax.swing.JFrame {

    static Connexion c = new Connexion();
    static PreparedStatement ps;
    PreparedStatement ps1;
    static DefaultTableModel dft = new DefaultTableModel();
    static ResultSet rs;
    ResultSet rs1;
    static ConnectPatient cp = new ConnectPatient();
    public static String prv = "";

    public AcceuilSecretaire() {
        initComponents();
        setLocationRelativeTo(this);
        actualiser();
        try {
            ps = c.connexionBdd().prepareStatement("select nom , prénom ,privilége from utilisateurs where nom_utilisateur=?");
            ps.setString(1, authentification.tusername.getText());
            rs = ps.executeQuery();
            while (rs.next()) {
                lnom.setText(rs.getString("nom") + " " + rs.getString("prénom"));
                prv = rs.getString("privilége");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AcceuilSecretaire.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        actualiser();
    }

    public static void actualiser() {
        
        dft.setRowCount(0);
        dft.setColumnCount(0);
        try {
            dft.addColumn("Matricule");
            dft.addColumn("Nom");
            dft.addColumn("Prénom");
            dft.addColumn("Né(e) le");
            dft.addColumn("N°Tél");
            dft.addColumn("Adresse");
            dft.addColumn("Sexe");
            dft.addColumn("Maladie");

            ps = c.connexionBdd().prepareStatement("select * from patient");
            rs = ps.executeQuery();
            while (rs.next()) {
                dft.addRow(new Object[]{
                    rs.getString("matricule_pat"),
                    rs.getString("nom_pat"),
                    rs.getString("prénom_pat"),
                    rs.getString("date_naissance"),
                    rs.getString("numTel"),
                    rs.getString("adresse_pat"),
                    rs.getString("sexe"),
                    rs.getString("maladie_pat")
                }
                );
            }
            tpatient.setModel(dft);
        } catch (SQLException ex) {
            Logger.getLogger(AcceuilSecretaire.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pafficher = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pajouter = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        psupprimer = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pdetails = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pmodifier = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pactualiser = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pimprimer = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pdeconnecter = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lnom = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        psalleattente = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jlabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cchercher = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tchercher = new javax.swing.JTextField();
        lchercher = new javax.swing.JLabel();
        lsalleattente = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpatient = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        iajouter = new javax.swing.JMenuItem();
        iactualiser = new javax.swing.JMenuItem();
        iimprimer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 531));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pafficher.setBackground(new java.awt.Color(0, 51, 102));
        pafficher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pafficherMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pafficherMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pafficherMouseExited(evt);
            }
        });
        pafficher.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Afficher");
        pafficher.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 60, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/voir.png"))); // NOI18N
        pafficher.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(pafficher, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, 40));

        pajouter.setBackground(new java.awt.Color(0, 51, 102));
        pajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pajouterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pajouterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pajouterMouseExited(evt);
            }
        });
        pajouter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Ajouter");
        pajouter.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ajouter-un-bouton (1) (1).png"))); // NOI18N
        pajouter.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 40));

        jPanel1.add(pajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 180, 40));

        psupprimer.setBackground(new java.awt.Color(0, 51, 102));
        psupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psupprimerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psupprimerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                psupprimerMouseExited(evt);
            }
        });
        psupprimer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Supprimer");
        psupprimer.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/garbage-bin (1).png"))); // NOI18N
        psupprimer.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(psupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 180, 40));

        pdetails.setBackground(new java.awt.Color(0, 51, 102));
        pdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pdetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pdetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pdetailsMouseExited(evt);
            }
        });
        pdetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Détails");
        pdetails.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/info.png"))); // NOI18N
        pdetails.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(pdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 180, 40));

        pmodifier.setBackground(new java.awt.Color(0, 51, 102));
        pmodifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pmodifierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pmodifierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pmodifierMouseExited(evt);
            }
        });
        pmodifier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Modifier");
        pmodifier.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report (1).png"))); // NOI18N
        pmodifier.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(pmodifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 180, 40));

        pactualiser.setBackground(new java.awt.Color(0, 51, 102));
        pactualiser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pactualiserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pactualiserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pactualiserMouseExited(evt);
            }
        });
        pactualiser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Actualiser");
        pactualiser.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/real-time (1).png"))); // NOI18N
        pactualiser.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(pactualiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 180, 40));

        pimprimer.setBackground(new java.awt.Color(0, 51, 102));
        pimprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pimprimerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pimprimerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pimprimerMouseExited(evt);
            }
        });
        pimprimer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Imprimer");
        pimprimer.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/printer (2).png"))); // NOI18N
        pimprimer.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(pimprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 180, 40));

        pdeconnecter.setBackground(new java.awt.Color(0, 51, 102));
        pdeconnecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pdeconnecterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pdeconnecterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pdeconnecterMouseExited(evt);
            }
        });
        pdeconnecter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Déconnecter");
        pdeconnecter.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/annuler.png"))); // NOI18N
        pdeconnecter.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(pdeconnecter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 180, 40));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nurse (1) (1).png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        lnom.setFont(new java.awt.Font("Harrington", 1, 14)); // NOI18N
        jPanel1.add(lnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 20));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, 3));

        psalleattente.setBackground(new java.awt.Color(0, 51, 102));
        psalleattente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psalleattenteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psalleattenteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                psalleattenteMouseExited(evt);
            }
        });
        psalleattente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("Salle d'atttente");
        psalleattente.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jlabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/waiting-room (1).png"))); // NOI18N
        jlabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel12MouseClicked(evt);
            }
        });
        psalleattente.add(jlabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(psalleattente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 180, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 590));

        jPanel2.setBackground(new java.awt.Color(90, 129, 168));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Table Patients :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        cchercher.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cchercher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matricule", "Nom", "Prénom" }));
        jPanel2.add(cchercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Recherche Par :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        tchercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tchercherActionPerformed(evt);
            }
        });
        jPanel2.add(tchercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 150, 30));

        lchercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loupe (1).png"))); // NOI18N
        lchercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lchercherMouseClicked(evt);
            }
        });
        jPanel2.add(lchercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, 30));

        lsalleattente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/waiting-room (1).png"))); // NOI18N
        lsalleattente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lsalleattenteMouseClicked(evt);
            }
        });
        jPanel2.add(lsalleattente, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 810, 110));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tpatient.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tpatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tpatient);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 810, 440));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel20.setText("Les patients :");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 810, 440));

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        iajouter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        iajouter.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        iajouter.setText("Ajouter patient");
        iajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iajouterActionPerformed(evt);
            }
        });
        jMenu1.add(iajouter);

        iactualiser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        iactualiser.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        iactualiser.setText("Actualiser");
        iactualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iactualiserActionPerformed(evt);
            }
        });
        jMenu1.add(iactualiser);

        iimprimer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        iimprimer.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        iimprimer.setText("Imprimer");
        iimprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iimprimerActionPerformed(evt);
            }
        });
        jMenu1.add(iimprimer);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iajouterActionPerformed
        ProfilePatient p = new ProfilePatient();
        p.setVisible(true);
    }//GEN-LAST:event_iajouterActionPerformed

    private void tchercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tchercherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tchercherActionPerformed

    private void iactualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iactualiserActionPerformed
        actualiser();
    }//GEN-LAST:event_iactualiserActionPerformed

    private void iimprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iimprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iimprimerActionPerformed

    private void pafficherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pafficherMouseClicked
        actualiser();
        tchercher.setText("");
    }//GEN-LAST:event_pafficherMouseClicked

    private void pajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pajouterMouseClicked
        if (prv.charAt(0) == '1') {
            ProfilePatient p = new ProfilePatient();
            p.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }

    }//GEN-LAST:event_pajouterMouseClicked

    private void pmodifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmodifierMouseClicked
        if (prv.charAt(1) == '1') {
            if (tpatient.getSelectedRowCount() == 1) {
                ProfilePatientMAJ ppm = new ProfilePatientMAJ();
                ppm.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }

    }//GEN-LAST:event_pmodifierMouseClicked

    private void psupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psupprimerMouseClicked
        if (prv.charAt(2) == '1') {
            if (tpatient.getSelectedRowCount() == 1) {
                if (JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer le patient", "confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    try {
                        ps = c.connexionBdd().prepareStatement("delete from patient where matricule_pat=?");
                        ps.setString(1, tpatient.getValueAt(tpatient.getSelectedRow(), 0) + "");
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Suppression faite avec succés");
                        actualiser();
                    } catch (SQLException ex) {
                        Logger.getLogger(AcceuilSecretaire.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }
    }//GEN-LAST:event_psupprimerMouseClicked

    private void pactualiserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pactualiserMouseClicked
        actualiser();
    }//GEN-LAST:event_pactualiserMouseClicked

    private void pimprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pimprimerMouseClicked
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_cabinet_medical", "root", "");
            String reportPath = "C:\\Users\\azus\\Documents\\NetBeansProjects\\gestion d'une cabinet medicale V7\\src\\EtatImpression\\ListePatients.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp, false);

        } catch (ClassNotFoundException | SQLException | JRException ex) {
            Logger.getLogger(AcceuilSecretaire.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pimprimerMouseClicked

    private void pdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdetailsMouseClicked
        if (prv.charAt(3) == '1') {
            if (tpatient.getSelectedRowCount() == 1) {
                DetailsPatient dp = new DetailsPatient();
                dp.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }
    }//GEN-LAST:event_pdetailsMouseClicked

    private void pdeconnecterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdeconnecterMouseClicked
        System.exit(0);
    }//GEN-LAST:event_pdeconnecterMouseClicked

    private void lchercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lchercherMouseClicked
        try {
            if (tchercher.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Veuillez renseigner le champs !!");
            } else {
                if (cchercher.getSelectedItem().equals("Matricule")) {
                    ps = c.connexionBdd().prepareStatement("select * from patient where matricule_pat=?");
                } else if (cchercher.getSelectedItem().equals("Nom")) {
                    ps = c.connexionBdd().prepareStatement("select * from patient where nom_pat=?");
                } else {
                    ps = c.connexionBdd().prepareStatement("select * from patient where prénom_pat=?");
                }
                ps.setString(1, tchercher.getText());
                rs = ps.executeQuery();
                dft.setRowCount(0);
                while (rs.next()) {
                    dft.addRow(new Object[]{
                        rs.getString("matricule_pat"),
                        rs.getString("nom_pat"),
                        rs.getString("prénom_pat"),
                        rs.getString("date_naissance"),
                        rs.getString("numTel"),
                        rs.getString("adresse_pat"),
                        rs.getString("sexe"),
                        rs.getString("maladie_pat")
                    }
                    );
                }
                tpatient.setModel(dft);
                if (dft.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "le patient n'existe pas");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(AcceuilSecretaire.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lchercherMouseClicked

    private void lsalleattenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsalleattenteMouseClicked
        if (prv.charAt(20) == '1') {
            boolean tr = false;
            if (tpatient.getSelectedRowCount() == 1) {
                try {
                    ps1 = c.connexionBdd().prepareStatement("select * from salle_attente");
                    rs1 = ps1.executeQuery();
                    while (rs1.next()) {
                        if (tpatient.getValueAt(tpatient.getSelectedRow(), 0).equals(rs1.getString("matricule_pat"))) {
                            tr = true;
                            break;
                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(AcceuilSecretaire.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (tr == false) {
                    try {
                        ps = c.connexionBdd().prepareStatement("insert into Salle_attente(matricule_pat) values(?)");
                        ps.setString(1, tpatient.getValueAt(tpatient.getSelectedRow(), 0) + "");
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(this, "le patient a été affecter a la salle d'attente");
                    } catch (SQLException ex) {
                        Logger.getLogger(ProfilePatient.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "le patient est déjà a la salle d'attente !");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }
    }//GEN-LAST:event_lsalleattenteMouseClicked

    private void pafficherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pafficherMouseEntered
        pafficher.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_pafficherMouseEntered

    private void pajouterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pajouterMouseEntered
        pajouter.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_pajouterMouseEntered

    private void pmodifierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmodifierMouseEntered
        pmodifier.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_pmodifierMouseEntered

    private void psupprimerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psupprimerMouseEntered
        psupprimer.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_psupprimerMouseEntered

    private void pactualiserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pactualiserMouseEntered
        pactualiser.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_pactualiserMouseEntered

    private void pimprimerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pimprimerMouseEntered
        pimprimer.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_pimprimerMouseEntered

    private void pdetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdetailsMouseEntered
        pdetails.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_pdetailsMouseEntered

    private void pdeconnecterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdeconnecterMouseEntered
        pdeconnecter.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_pdeconnecterMouseEntered

    private void pafficherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pafficherMouseExited
        pafficher.setBackground(new java.awt.Color(0,51,102));
    }//GEN-LAST:event_pafficherMouseExited

    private void pajouterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pajouterMouseExited
        pajouter.setBackground(new java.awt.Color(0,51,102));
    }//GEN-LAST:event_pajouterMouseExited

    private void pmodifierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmodifierMouseExited
        pmodifier.setBackground(new java.awt.Color(0,51,102));
    }//GEN-LAST:event_pmodifierMouseExited

    private void psupprimerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psupprimerMouseExited
        psupprimer.setBackground(new java.awt.Color(0,51,102));
    }//GEN-LAST:event_psupprimerMouseExited

    private void pactualiserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pactualiserMouseExited
        pactualiser.setBackground(new java.awt.Color(0,51,102));
    }//GEN-LAST:event_pactualiserMouseExited

    private void pimprimerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pimprimerMouseExited
        pimprimer.setBackground(new java.awt.Color(0,51,102));
    }//GEN-LAST:event_pimprimerMouseExited

    private void pdetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdetailsMouseExited
        pdetails.setBackground(new java.awt.Color(0,51,102));
    }//GEN-LAST:event_pdetailsMouseExited

    private void pdeconnecterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdeconnecterMouseExited
        pdeconnecter.setBackground(new java.awt.Color(0,51,102));
    }//GEN-LAST:event_pdeconnecterMouseExited

    private void jlabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel12MouseClicked

    }//GEN-LAST:event_jlabel12MouseClicked

    private void psalleattenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalleattenteMouseClicked
        if (prv.charAt(22) == '1') {
            SalleAttente sa = new SalleAttente();
            sa.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }
    }//GEN-LAST:event_psalleattenteMouseClicked

    private void psalleattenteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalleattenteMouseEntered
        psalleattente.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_psalleattenteMouseEntered

    private void psalleattenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalleattenteMouseExited
        psalleattente.setBackground(new java.awt.Color(0,51,102));
    }//GEN-LAST:event_psalleattenteMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcceuilSecretaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcceuilSecretaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcceuilSecretaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcceuilSecretaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcceuilSecretaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cchercher;
    private javax.swing.JMenuItem iactualiser;
    private javax.swing.JMenuItem iajouter;
    private javax.swing.JMenuItem iimprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel12;
    private javax.swing.JLabel lchercher;
    private javax.swing.JLabel lnom;
    private javax.swing.JLabel lsalleattente;
    private javax.swing.JPanel pactualiser;
    private javax.swing.JPanel pafficher;
    private javax.swing.JPanel pajouter;
    private javax.swing.JPanel pdeconnecter;
    private javax.swing.JPanel pdetails;
    private javax.swing.JPanel pimprimer;
    private javax.swing.JPanel pmodifier;
    private javax.swing.JPanel psalleattente;
    private javax.swing.JPanel psupprimer;
    private javax.swing.JTextField tchercher;
    public static javax.swing.JTable tpatient;
    // End of variables declaration//GEN-END:variables
}
