/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.*;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author azus
 */
public class ADDOrdonance extends javax.swing.JFrame {

    Connexion c = new Connexion();
    PreparedStatement ps, ps1;
    DefaultTableModel dft = new DefaultTableModel();
    ResultSet rs;
    boolean tr = false;

    /**
     * Creates new form ADDOrdonance
     */
    public ADDOrdonance() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        try {
            ps = c.connexionBdd().prepareStatement("select * from patient where matricule_pat=?");
            ps.setString(1, PageConsultations.tconsultation.getValueAt(PageConsultations.tconsultation.getSelectedRow(), 3) + "");
            rs = ps.executeQuery();
            while (rs.next()) {
                lmatricule.setText(rs.getString("matricule_pat"));
                lnom.setText(rs.getString("nom_pat") + " " + rs.getString("prénom_pat"));
                byte[] photo = rs.getBytes("photo_patient");
                ImageIcon imgic = new ImageIcon(photo);
                Image img = imgic.getImage().getScaledInstance(limage.getWidth(), limage.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imgf = new ImageIcon(img);
                limage.setIcon(imgf);
                tpath.setText(rs.getString("tpath"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ADDOrdonance.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void reset() {
        tnommed.setText(null);
        tfamille.setText(null);
        tforme.setText(null);
        tdosage.setText(null);
        tposologie.setText(null);
        tobservation.setText(null);
        tquantite.setText(null);
    }

    public void Actualiser() {
        dft.setRowCount(0);
        dft.setColumnCount(0);
        try {
            dft.addColumn("ID");
            dft.addColumn("Médicament");
            dft.addColumn("Famille");
            dft.addColumn("Forme");
            dft.addColumn("Dosage");
            dft.addColumn("Posologie");
            dft.addColumn("Quantité");

            ps = c.connexionBdd().prepareStatement("select * from medicament where ordonnance_id= ?");
            ps.setString(1, lordonance.getText());
            rs = ps.executeQuery();
            while (rs.next()) {
                dft.addRow(new Object[]{
                    rs.getString("medicament_id"),
                    rs.getString("nom_med"),
                    rs.getString("famille_med"),
                    rs.getString("forme"),
                    rs.getString("dosage"),
                    rs.getString("posologie_usuelle"),
                    rs.getString("qte_med")
                }
                );
            }
            tmedicament.setModel(dft);
        } catch (SQLException ex) {
            Logger.getLogger(ADDOrdonance.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpath = new javax.swing.JLabel();
        lordonance = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        limage = new javax.swing.JLabel();
        lnom = new javax.swing.JLabel();
        lmatricule = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tmedicament = new javax.swing.JTable();
        jdate = new com.toedter.calendar.JDateChooser();
        bmodifier = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bsupprimer = new javax.swing.JButton();
        bquitter = new javax.swing.JButton();
        bajout = new javax.swing.JButton();
        tdure = new javax.swing.JTextField();
        tfamille = new javax.swing.JTextField();
        tdosage = new javax.swing.JTextField();
        tquantite = new javax.swing.JTextField();
        tposologie = new javax.swing.JTextField();
        tforme = new javax.swing.JTextField();
        tobservation = new javax.swing.JTextField();
        tnommed = new javax.swing.JTextField();
        bimprimer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        lordonance.setText("..");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Date* :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jLabel3.setText("Duré traitement* :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(limage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 60));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 60));

        lnom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lnom.setText("....");
        getContentPane().add(lnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        lmatricule.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lmatricule.setText(".............");
        getContentPane().add(lmatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Les Medicaments");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        tmedicament.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Médicament", "Famille", "Forme", "Dosage", "Posologie", "Quantité"
            }
        ));
        tmedicament.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmedicamentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tmedicament);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 680, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 680, 310));
        getContentPane().add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 150, -1));

        bmodifier.setText("Modifier");
        bmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodifierActionPerformed(evt);
            }
        });
        getContentPane().add(bmodifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        jLabel5.setText("Dosage* :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));

        jLabel6.setText("Posologie usuelle* :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jLabel7.setText("Famille* :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jLabel8.setText("Forme* :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        jLabel9.setText("Observation :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        jLabel10.setText("Quantité* :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 20));

        jLabel11.setText("Medicament* :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        bsupprimer.setText("Supprimer");
        bsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(bsupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, -1, -1));

        bquitter.setText("Quitter");
        bquitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bquitterActionPerformed(evt);
            }
        });
        getContentPane().add(bquitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, -1, -1));

        bajout.setText("Ajouter");
        bajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajoutActionPerformed(evt);
            }
        });
        getContentPane().add(bajout, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));
        getContentPane().add(tdure, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 150, -1));
        getContentPane().add(tfamille, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 90, -1));
        getContentPane().add(tdosage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 90, -1));
        getContentPane().add(tquantite, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 90, -1));
        getContentPane().add(tposologie, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 90, -1));
        getContentPane().add(tforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 90, -1));
        getContentPane().add(tobservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 90, -1));
        getContentPane().add(tnommed, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 90, -1));

        bimprimer.setText("Imprimer");
        bimprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bimprimerActionPerformed(evt);
            }
        });
        getContentPane().add(bimprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, -1, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajoutActionPerformed
        if (tdure.getText().isEmpty() || tnommed.getText().isEmpty() || tdosage.getText().isEmpty()
                || jdate.getDate() == null || tquantite.getText().isEmpty()
                || tfamille.getText().isEmpty() || tposologie.getText().isEmpty() || tforme.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez Renseigner tout les champs !!");
        } else {
            try {
                if (tr == false) {
                    ps1 = c.connexionBdd().prepareStatement("insert into ordonnance(date_or,duré_trait,matricule_pat,medecin_id,consultation_id) values(?,?,?,?,?)");
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    String daten = sdf.format(jdate.getDate());
                    ps1.setString(1, daten);
                    ps1.setString(2, tdure.getText());
                    ps1.setString(3, lmatricule.getText());
                    ps1.setString(4, authentification.tusername.getText());
                    ps1.setString(5, PageConsultations.tconsultation.getValueAt(PageConsultations.tconsultation.getSelectedRow(), 0) + "");
                    ps1.executeUpdate();

                    ps1 = c.connexionBdd().prepareStatement("select ordonnance_id from ordonnance ORDER by ordonnance_id DESC limit 1");
                    rs = ps1.executeQuery();
                    while (rs.next()) {
                        lordonance.setText(rs.getString("ordonnance_id"));
                    }
                    tr = true;
                }
                ps = c.connexionBdd().prepareStatement("insert into medicament(ordonnance_id,nom_med,famille_med,forme,dosage,posologie_usuelle,observation,qte_med) values(?,?,?,?,?,?,?,?)");
                ps.setString(1, lordonance.getText());
                ps.setString(2, tnommed.getText());
                ps.setString(3, tfamille.getText());
                ps.setString(4, tforme.getText());
                ps.setString(5, tdosage.getText());
                ps.setString(6, tposologie.getText());
                ps.setString(7, tobservation.getText());
                ps.setString(8, tquantite.getText());
                ps.executeUpdate();
                Actualiser();
                reset();
                tdure.setEditable(false);

            } catch (SQLException ex) {
                Logger.getLogger(ADDOrdonance.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_bajoutActionPerformed

    private void bquitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bquitterActionPerformed
        dispose();
    }//GEN-LAST:event_bquitterActionPerformed

    private void bmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodifierActionPerformed
        if (tmedicament.getSelectedRowCount() == 1) {

            if (JOptionPane.showConfirmDialog(this, "Voullez vous vraiment modifier?",
                    "Confirmation de modification",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    ps = c.connexionBdd().prepareStatement("update medicament set nom_med=?, famille_med=? ,forme=? ,dosage=? ,posologie_usuelle=? ,observation=? ,qte_med=? where medicament_id=?");
                    ps.setString(1, tnommed.getText());
                    ps.setString(2, tfamille.getText());
                    ps.setString(3, tforme.getText());
                    ps.setString(4, tdosage.getText());
                    ps.setString(5, tposologie.getText());
                    ps.setString(6, tobservation.getText());
                    ps.setString(7, tquantite.getText());
                    ps.setString(8, tmedicament.getValueAt(tmedicament.getSelectedRow(), 0) + "");
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Mise à jour faites avec succés");
                    Actualiser();
                    reset();
                } catch (SQLException ex) {
                    Logger.getLogger(ADDOrdonance.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_bmodifierActionPerformed

    private void bsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsupprimerActionPerformed
        if (tmedicament.getSelectedRowCount() == 1) {
            if (JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer le medicament", "confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    ps = c.connexionBdd().prepareStatement("delete from medicament where medicament_id=?");
                    ps.setString(1, tmedicament.getValueAt(tmedicament.getSelectedRow(), 0) + "");
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Suppression avec faite succés");
                    Actualiser();
                } catch (SQLException ex) {
                    Logger.getLogger(ADDOrdonance.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_bsupprimerActionPerformed

    private void tmedicamentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmedicamentMouseClicked
        try {
            ps = c.connexionBdd().prepareStatement("select * from medicament where medicament_id=?");
            ps.setString(1, tmedicament.getValueAt(tmedicament.getSelectedRow(), 0) + "");
            rs = ps.executeQuery();
            while (rs.next()) {
                tnommed.setText(rs.getString("nom_med"));
                tfamille.setText(rs.getString("famille_med"));
                tforme.setText(rs.getString("forme"));
                tdosage.setText(rs.getString("dosage"));
                tposologie.setText(rs.getString("posologie_usuelle"));
                tobservation.setText(rs.getString("observation"));
                tquantite.setText(rs.getString("qte_med"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ADDOrdonance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tmedicamentMouseClicked

    private void bimprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bimprimerActionPerformed
        if (Médecin.prv.charAt(19) == '1') {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_cabinet_medical", "root", "");
                JasperDesign jdesing = JRXmlLoader.load("C:\\Users\\azus\\Documents\\NetBeansProjects\\gestion d'une cabinet medicale V7\\src\\EtatImpression\\FicheOrdonnance1.jrxml");
                String query = "Select ordonnance.* , medicament.*, utilisateurs.nom as nom ,patient.nom_pat,patient.prénom_pat,patient.date_naissance , medecin.specialite from ordonnance left join medicament on (medicament.ordonnance_id=ordonnance.ordonnance_id) left join patient on (patient.matricule_pat=ordonnance.matricule_pat) LEFT join medecin on (ordonnance.medecin_id=medecin.nom_utilisateur) left join utilisateurs on (medecin.nom_utilisateur=utilisateurs.nom_utilisateur) where ordonnance.ordonnance_id='" + lordonance.getText() + "'";
                JRDesignQuery updateQuery = new JRDesignQuery();
                updateQuery.setText(query);
                jdesing.setQuery(updateQuery);
                JasperReport jreport = JasperCompileManager.compileReport(jdesing);
                JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);

                JasperViewer.viewReport(jprint);

            } catch (ClassNotFoundException | SQLException | JRException ex) {
                Logger.getLogger(OrdonnanceVue.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }
    }//GEN-LAST:event_bimprimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADDOrdonance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADDOrdonance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADDOrdonance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADDOrdonance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADDOrdonance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bajout;
    private javax.swing.JButton bimprimer;
    private javax.swing.JButton bmodifier;
    private javax.swing.JButton bquitter;
    private javax.swing.JButton bsupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JLabel limage;
    private javax.swing.JLabel lmatricule;
    private javax.swing.JLabel lnom;
    private javax.swing.JLabel lordonance;
    private javax.swing.JTextField tdosage;
    private javax.swing.JTextField tdure;
    private javax.swing.JTextField tfamille;
    private javax.swing.JTextField tforme;
    private javax.swing.JTable tmedicament;
    private javax.swing.JTextField tnommed;
    private javax.swing.JTextField tobservation;
    private javax.swing.JLabel tpath;
    private javax.swing.JTextField tposologie;
    private javax.swing.JTextField tquantite;
    // End of variables declaration//GEN-END:variables
}
