/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.*;
import java.awt.Image;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Properties;
import javax.swing.JFrame;

/**
 *
 * @author azus
 */
public class DetailsRDVMAJ extends javax.swing.JFrame {

    /**
     * Creates new form DetailsRDVMAJ
     */
    Connexion c = new Connexion();
    PreparedStatement ps, ps1;
    DefaultTableModel dft = new DefaultTableModel();
    ResultSet rs, rs1;

    public DetailsRDVMAJ() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        try {
            ps = c.connexionBdd().prepareStatement("select * from patient where matricule_pat=?");
            ps.setString(1, DetailsPatient.tmatricule.getText());
            rs = ps.executeQuery();
            while (rs.next()) {
                lmatricule.setText(rs.getString("matricule_pat"));
                lnom.setText(rs.getString("nom_pat") + " " + rs.getString("prénom_pat"));
                byte[] photo = rs.getBytes("photo_patient");
                ImageIcon imgic = new ImageIcon(photo);
                Image img = imgic.getImage().getScaledInstance(limage.getWidth(), limage.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imgf = new ImageIcon(img);
                limage.setIcon(imgf);
                tpath.setText(rs.getString("tpath"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DetailsRDVMAJ.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ps = c.connexionBdd().prepareStatement("select * from rendez_vous where rdv_id=?");
            ps.setString(1, DetailsPatient.trendezvous.getValueAt(DetailsPatient.trendezvous.getSelectedRow(), 0) + "");
            rs = ps.executeQuery();
            while (rs.next()) {
                lnumrdv.setText(rs.getString("rdv_id"));

                ps1 = c.connexionBdd().prepareStatement("select* from utilisateurs where nom_utilisateur=? and type_utilisateur='Médecin' ");
                ps1.setString(1, rs.getString("médecin_id"));
                rs1 = ps1.executeQuery();
                while (rs1.next()) {
                    tnom.setText(rs1.getString("nom"));
                    tprenom.setText(rs1.getString("prénom"));
                }
                jdate.setDate(rs.getDate("daterdv"));
                theure.setSelectedItem(rs.getString("heure"));
                tmotif.setText(rs.getString("motif_visite"));
                jstatut.setSelectedItem(rs.getString("statut"));
                tnote.setText(rs.getString("note"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DetailsRDVMAJ.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpath = new javax.swing.JTextField();
        tmotif = new javax.swing.JTextField();
        jdate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tnote = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        lnumrdv = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        limage = new javax.swing.JLabel();
        lnom = new javax.swing.JLabel();
        lmatricule = new javax.swing.JLabel();
        bquitter = new javax.swing.JButton();
        bsauvgarder = new javax.swing.JButton();
        jstatut = new javax.swing.JComboBox<>();
        theure = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tnom = new javax.swing.JTextField();
        tprenom = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tmotif.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(tmotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 150, -1));
        getContentPane().add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 150, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Heure * :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Motif * :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("statut * :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Date * :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Notes :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        tnote.setColumns(20);
        tnote.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tnote.setRows(5);
        jScrollPane1.setViewportView(tnote);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 750, 130));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("N° Rendez-vous :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        lnumrdv.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lnumrdv.setText(".......");
        getContentPane().add(lnumrdv, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(limage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 60));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 60));

        lnom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lnom.setText("....");
        getContentPane().add(lnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        lmatricule.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lmatricule.setText(".............");
        getContentPane().add(lmatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        bquitter.setBackground(new java.awt.Color(255, 0, 0));
        bquitter.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bquitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/croix.png"))); // NOI18N
        bquitter.setText("Quitter");
        bquitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bquitterActionPerformed(evt);
            }
        });
        getContentPane().add(bquitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, -1, -1));

        bsauvgarder.setBackground(new java.awt.Color(0, 204, 204));
        bsauvgarder.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bsauvgarder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/verifier.png"))); // NOI18N
        bsauvgarder.setText("Enregistrer");
        bsauvgarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsauvgarderActionPerformed(evt);
            }
        });
        getContentPane().add(bsauvgarder, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, -1, -1));

        jstatut.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jstatut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Confirmé", "Annulé", "En attente" }));
        getContentPane().add(jstatut, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 120, -1));

        theure.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        theure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00:00", "08:30:00", "09:00:00", "09:30:00", "10:00:00", "10:30:00", "11:00:00", "11:30:00", "12:00:00", "12:30:00", "13:00:00", "13:30:00", "14:00:00", "14:30:00", "15:00:00", "15:30:00", "16:00:00", "16:30:00", "17:00:00", "17:30:00" }));
        getContentPane().add(theure, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 120, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Nom Medécin * :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Prénom Medécin * :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));
        getContentPane().add(tnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 130, -1));
        getContentPane().add(tprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bquitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bquitterActionPerformed
        dispose();
    }//GEN-LAST:event_bquitterActionPerformed

    private void bsauvgarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsauvgarderActionPerformed
        if (tmotif.getText().isEmpty() || jdate.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner tout les champs");
        } else if (JOptionPane.showConfirmDialog(this, "Voullez vous vraiment modifier?",
                "Confirmation de modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            boolean tr = false;
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(jdate.getDate());
            try {
                String idmed = "";
                ps = c.connexionBdd().prepareStatement("select nom_utilisateur from utilisateurs where nom=? and prénom=? and type_utilisateur='Médecin' ");
                ps.setString(1,tnom.getText());
                ps.setString(2, tprenom.getText());
                rs = ps.executeQuery();
                while (rs.next()) {
                    idmed = rs.getString("nom_utilisateur");
                }
                if (idmed.equals("")) {
                    JOptionPane.showMessageDialog(this, "Le médecin n'existe pas !!");
                } else {
                    ps = c.connexionBdd().prepareStatement("select * from rendez_vous where rdv_id<>?");
                    ps.setString(1, lnumrdv.getText());
                    rs = ps.executeQuery();
                    while (rs.next()) {
                        if ((idmed.equals(rs.getString("médecin_id")))
                                && (theure.getSelectedItem().equals(rs.getString("heure")))
                                && (date.equals(rs.getDate("daterdv") + ""))) {
                            tr = true;
                            JOptionPane.showMessageDialog(this, "Le rendez-vous est déjà  pris !! ");
                            break;
                        }
                    }
                    if (tr == false) {
                        try {
                            ps = c.connexionBdd().prepareStatement("update rendez_vous set médecin_id=?, daterdv=? ,heure=? ,motif_visite=? ,statut=? ,note=? where rdv_id=?");
                            ps.setString(1, idmed);
                            ps.setString(2, date);
                            ps.setString(3, theure.getSelectedItem() + "");
                            ps.setString(4, tmotif.getText());
                            ps.setString(5, jstatut.getSelectedItem() + "");
                            ps.setString(6, tnote.getText());
                            ps.setString(7, lnumrdv.getText());
                            ps.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Mise à jour faites avec succés");
                            DetailsPatient.actualiserRDV();
                            dispose();
                        } catch (SQLException ex) {
                            Logger.getLogger(DetailsRDVMAJ.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }

            } catch (SQLException ex) {
                Logger.getLogger(DetailsRDVMAJ.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_bsauvgarderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsRDVMAJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsRDVMAJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsRDVMAJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsRDVMAJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailsRDVMAJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bquitter;
    private javax.swing.JButton bsauvgarder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JComboBox<String> jstatut;
    private javax.swing.JLabel limage;
    private javax.swing.JLabel lmatricule;
    private javax.swing.JLabel lnom;
    private javax.swing.JLabel lnumrdv;
    private javax.swing.JComboBox<String> theure;
    private javax.swing.JTextField tmotif;
    private javax.swing.JTextField tnom;
    private javax.swing.JTextArea tnote;
    private javax.swing.JTextField tpath;
    private javax.swing.JTextField tprenom;
    // End of variables declaration//GEN-END:variables
}
