/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Controleur.*;
import Modele.*;
import java.awt.Image;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author azus
 */
public class DetailsConsultationMedecin extends javax.swing.JFrame {

    Connexion c = new Connexion();
    PreparedStatement ps, ps1;
    DefaultTableModel dft = new DefaultTableModel();
    ResultSet rs;

    /**
     * Creates new form DetailsConsultationMedecin
     */
    public DetailsConsultationMedecin() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        try {
            ps = c.connexionBdd().prepareStatement("select * from patient where matricule_pat=?");
            ps.setString(1, PageConsultations.tconsultation.getValueAt(PageConsultations.tconsultation.getSelectedRow(), 3) + "");
            rs = ps.executeQuery();
            while (rs.next()) {
                lmatricule.setText(rs.getString("matricule_pat"));
                lnom.setText(rs.getString("nom_pat") + " " + rs.getString("prénom_pat"));
                tantchirurgicaux.setText(rs.getString("antécédents_chirurgicaux"));
                tantfamiliaux.setText(rs.getString("antécédents_familiaux"));
                tantmedicaux.setText(rs.getString("antécédents_médicaux"));
                tantpersonnels.setText(rs.getString("antécédents_personnels"));
                byte[] photo = rs.getBytes("photo_patient");
                ImageIcon imgic = new ImageIcon(photo);
                Image img = imgic.getImage().getScaledInstance(limage.getWidth(), limage.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imgf = new ImageIcon(img);
                limage.setIcon(imgf);
                tpath.setText(rs.getString("tpath"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DetailsConsultationMedecin.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            ps = c.connexionBdd().prepareStatement("select * from consultation where consultation_id=?");
            ps.setString(1, PageConsultations.tconsultation.getValueAt(PageConsultations.tconsultation.getSelectedRow(), 0) + "");
            rs = ps.executeQuery();
            while (rs.next()) {
                lnumcons.setText(rs.getString("consultation_id"));
                jdate.setDate(rs.getDate("date_cons"));
                tmotif.setText(rs.getString("motif"));
                tpoids.setText(rs.getString("poids"));
                ttaille.setText(rs.getString("taille"));
                ttempérature.setText(rs.getString("température"));
                tfrequence.setText(rs.getString("fréquence_cardiaque"));
                tglycemie.setText(rs.getString("glycémie"));
                tpression.setText(rs.getString("pression_artérielle"));
                timc.setText(rs.getString("imc"));
                tdecision.setText(rs.getString("imcdec"));
                tobservation.setText(rs.getString("observation"));
                tresultat.setText(rs.getString("résultat_cons"));
                tdiagnostique.setText(rs.getString("diagnostique"));
                tmontant.setText(rs.getString("prix_consultation"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DetailsConsultationMedecin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpath = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tresultat = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tdiagnostique = new javax.swing.JTextArea();
        tmontant = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        limage = new javax.swing.JLabel();
        lnom = new javax.swing.JLabel();
        jdate = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tpoids = new javax.swing.JTextField();
        ttaille = new javax.swing.JTextField();
        ttempérature = new javax.swing.JTextField();
        tfrequence = new javax.swing.JTextField();
        tpression = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tobservation = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tantpersonnels = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        tantfamiliaux = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        tantmedicaux = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        tantchirurgicaux = new javax.swing.JTextArea();
        tglycemie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bimc = new javax.swing.JButton();
        tdecision = new javax.swing.JTextField();
        timc = new javax.swing.JTextField();
        lmatricule = new javax.swing.JLabel();
        tmotif = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lnumcons = new javax.swing.JLabel();
        bsauvgarder = new javax.swing.JButton();
        bannuler = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lfond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel34.setText("Diagnostique médical * :");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, -1, -1));

        tresultat.setColumns(20);
        tresultat.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tresultat.setRows(5);
        jScrollPane1.setViewportView(tresultat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 330, 110));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel35.setText("Résultat de l'examen * :");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Montant * :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, -1, -1));

        tdiagnostique.setColumns(20);
        tdiagnostique.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tdiagnostique.setRows(5);
        jScrollPane2.setViewportView(tdiagnostique);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 341, 330, 90));

        tmontant.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(tmontant, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 300, 30));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(limage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 60));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 60));

        lnom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lnom.setText("....");
        getContentPane().add(lnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));
        getContentPane().add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 220, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("Date * :");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("Motif * :");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, -1, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setText("Taille (m) * :");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel29.setText("Poids (kg) * :");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel30.setText("Fréquence cardiaque * :");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel31.setText("Températur (C°) * :");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        tpoids.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tpoids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpoidsActionPerformed(evt);
            }
        });
        getContentPane().add(tpoids, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 90, -1));

        ttaille.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ttaille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttailleActionPerformed(evt);
            }
        });
        getContentPane().add(ttaille, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 90, -1));

        ttempérature.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ttempérature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttempératureActionPerformed(evt);
            }
        });
        getContentPane().add(ttempérature, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 90, -1));

        tfrequence.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfrequence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfrequenceActionPerformed(evt);
            }
        });
        getContentPane().add(tfrequence, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 90, -1));

        tpression.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tpression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpressionActionPerformed(evt);
            }
        });
        getContentPane().add(tpression, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 90, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Observation * :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, -1, -1));

        tobservation.setColumns(20);
        tobservation.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tobservation.setRows(5);
        jScrollPane7.setViewportView(tobservation);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 240, 120));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Antécédents personnels :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Antécédents familiaux :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Antécédents médicaux :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Antécédents chirurgicaux");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        tantpersonnels.setEditable(false);
        tantpersonnels.setColumns(20);
        tantpersonnels.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tantpersonnels.setRows(5);
        jScrollPane3.setViewportView(tantpersonnels);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 260, -1));

        tantfamiliaux.setEditable(false);
        tantfamiliaux.setColumns(20);
        tantfamiliaux.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tantfamiliaux.setRows(5);
        jScrollPane4.setViewportView(tantfamiliaux);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 260, -1));

        tantmedicaux.setEditable(false);
        tantmedicaux.setColumns(20);
        tantmedicaux.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tantmedicaux.setRows(5);
        jScrollPane5.setViewportView(tantmedicaux);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 260, -1));

        tantchirurgicaux.setEditable(false);
        tantchirurgicaux.setColumns(20);
        tantchirurgicaux.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tantchirurgicaux.setRows(5);
        jScrollPane6.setViewportView(tantchirurgicaux);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 260, -1));

        tglycemie.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tglycemie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglycemieActionPerformed(evt);
            }
        });
        getContentPane().add(tglycemie, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 90, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Pression Artérielle * :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Glycémie * :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        bimc.setBackground(new java.awt.Color(0, 255, 255));
        bimc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bimc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IMC - copie.png"))); // NOI18N
        bimc.setText("Calculer IMC");
        bimc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bimcActionPerformed(evt);
            }
        });
        getContentPane().add(bimc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 230, 30));

        tdecision.setEditable(false);
        tdecision.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(tdecision, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 110, -1));

        timc.setEditable(false);
        timc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(timc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 110, -1));

        lmatricule.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lmatricule.setText(".............");
        getContentPane().add(lmatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        tmotif.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(tmotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 220, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("N° Consultation :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        lnumcons.setText("...");
        getContentPane().add(lnumcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        bsauvgarder.setBackground(new java.awt.Color(0, 204, 204));
        bsauvgarder.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bsauvgarder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/verifier.png"))); // NOI18N
        bsauvgarder.setText("Enregistrer");
        bsauvgarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsauvgarderActionPerformed(evt);
            }
        });
        getContentPane().add(bsauvgarder, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 660, 130, -1));

        bannuler.setBackground(new java.awt.Color(255, 0, 0));
        bannuler.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bannuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/croix.png"))); // NOI18N
        bannuler.setText("Annuler");
        bannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bannulerActionPerformed(evt);
            }
        });
        getContentPane().add(bannuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 660, -1, -1));

        jPanel3.setBackground(new java.awt.Color(227, 226, 226));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 90));

        lfond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Consultation.png"))); // NOI18N
        getContentPane().add(lfond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tpoidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpoidsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpoidsActionPerformed

    private void ttailleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttailleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttailleActionPerformed

    private void ttempératureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttempératureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttempératureActionPerformed

    private void tfrequenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfrequenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfrequenceActionPerformed

    private void tpressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpressionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpressionActionPerformed

    private void tglycemieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglycemieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglycemieActionPerformed

    private void bimcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bimcActionPerformed
        if (ttaille.getText().isEmpty() || tpoids.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez saisir la taille et le poids d'abord !!");
        } else {
            timc.setText(CalculerIMC.calcul(Float.parseFloat(ttaille.getText()), Float.parseFloat(tpoids.getText())) + "");
            tdecision.setText(CalculerIMC.typeIMC(Float.parseFloat(timc.getText())));
        }
    }//GEN-LAST:event_bimcActionPerformed

    private void bsauvgarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsauvgarderActionPerformed
        if (jdate.getDate() == null || tmotif.getText().isEmpty()
                || ttaille.getText().isEmpty() || tpoids.getText().isEmpty() || ttempérature.getText().isEmpty() || tfrequence.getText().isEmpty()
                || tglycemie.getText().isEmpty() || tpression.getText().isEmpty() || timc.getText().isEmpty() || tdecision.getText().isEmpty()
                || tobservation.getText().isEmpty() || tresultat.getText().isEmpty() || tdiagnostique.getText().isEmpty() || tmontant.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner tout les champs");
        } else if (JOptionPane.showConfirmDialog(this, "Voullez vous vraiment modifier?",
                "Confirmation de modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                ps = c.connexionBdd().prepareStatement("update consultation set date_cons=? ,motif=? , taille=? ,poids=?, température=? ,fréquence_cardiaque=? ,glycémie=? ,pression_artérielle=? ,imc=? ,imcdec=?,observation=?,résultat_cons=? ,diagnostique=?,prix_consultation=? where consultation_id=? ");
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String daten = sdf.format(jdate.getDate());
                ps.setString(1, daten);
                ps.setString(2, tmotif.getText());
                ps.setString(3, ttaille.getText());
                ps.setString(4, tpoids.getText());
                ps.setString(5, ttempérature.getText());
                ps.setString(6, tfrequence.getText());
                ps.setString(7, tglycemie.getText());
                ps.setString(8, tpression.getText());
                ps.setString(9, timc.getText());
                ps.setString(10, tdecision.getText());
                ps.setString(11, tobservation.getText());
                ps.setString(12, tresultat.getText());
                ps.setString(13, tdiagnostique.getText());
                ps.setString(14, tmontant.getText());
                ps.setString(15, lnumcons.getText());
                ps.executeUpdate();
                ps1 = c.connexionBdd().prepareStatement("update facture set montant=? ,reste=? where consultation_id=?");
                ps1.setString(1, tmontant.getText());
                ps1.setString(2, tmontant.getText());
                ps1.setString(3, lnumcons.getText());
                ps1.executeUpdate();
                PageConsultations.actualiserc();
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(DetailsConsultationMedecin.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_bsauvgarderActionPerformed

    private void bannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bannulerActionPerformed
        dispose();
    }//GEN-LAST:event_bannulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsConsultationMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsConsultationMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsConsultationMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsConsultationMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailsConsultationMedecin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bannuler;
    private javax.swing.JButton bimc;
    private javax.swing.JButton bsauvgarder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JLabel lfond;
    private javax.swing.JLabel limage;
    private javax.swing.JLabel lmatricule;
    private javax.swing.JLabel lnom;
    private javax.swing.JLabel lnumcons;
    private javax.swing.JTextArea tantchirurgicaux;
    private javax.swing.JTextArea tantfamiliaux;
    private javax.swing.JTextArea tantmedicaux;
    private javax.swing.JTextArea tantpersonnels;
    private javax.swing.JTextField tdecision;
    private javax.swing.JTextArea tdiagnostique;
    private javax.swing.JTextField tfrequence;
    private javax.swing.JTextField tglycemie;
    private javax.swing.JTextField timc;
    private javax.swing.JTextField tmontant;
    private javax.swing.JTextField tmotif;
    private javax.swing.JTextArea tobservation;
    private javax.swing.JLabel tpath;
    private javax.swing.JTextField tpoids;
    private javax.swing.JTextField tpression;
    private javax.swing.JTextArea tresultat;
    private javax.swing.JTextField ttaille;
    private javax.swing.JTextField ttempérature;
    // End of variables declaration//GEN-END:variables
}
