/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.*;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controleur.*;
import java.text.DecimalFormat;
import javax.swing.JFrame;

/**
 *
 * @author azus
 */
public class DetailsConsultation extends javax.swing.JFrame {

    Connexion c = new Connexion();
    PreparedStatement ps, ps1, ps0;
    DefaultTableModel dft = new DefaultTableModel();
    ResultSet rs;

    public DetailsConsultation() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        try {
            ps = c.connexionBdd().prepareStatement("select * from patient where matricule_pat=?");
            ps.setString(1, DetailsPatient.tmatricule.getText());
            rs = ps.executeQuery();
            while (rs.next()) {
                lmatricule.setText(rs.getString("matricule_pat"));
                lnom.setText(rs.getString("nom_pat") + " " + rs.getString("prénom_pat"));
                tantchirurgicaux.setText(rs.getString("antécédents_chirurgicaux"));
                tantfamiliaux.setText(rs.getString("antécédents_familiaux"));
                tantmedicaux.setText(rs.getString("antécédents_médicaux"));
                tantpersonnels.setText(rs.getString("antécédents_personnels"));
                byte[] photo = rs.getBytes("photo_patient");
                ImageIcon imgic = new ImageIcon(photo);
                Image img = imgic.getImage().getScaledInstance(limage.getWidth(), limage.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imgf = new ImageIcon(img);
                limage.setIcon(imgf);
                tpath.setText(rs.getString("tpath"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DetailsConsultation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpath = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jdate = new com.toedter.calendar.JDateChooser();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tpoids = new javax.swing.JTextField();
        ttaille = new javax.swing.JTextField();
        ttempérature = new javax.swing.JTextField();
        tfrequence = new javax.swing.JTextField();
        tpression = new javax.swing.JTextField();
        bajouter = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tobservation = new javax.swing.JTextArea();
        bquitter = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tantpersonnels = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        tantfamiliaux = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        tantmedicaux = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        tantchirurgicaux = new javax.swing.JTextArea();
        tglycemie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bimc = new javax.swing.JButton();
        tdecision = new javax.swing.JTextField();
        timc = new javax.swing.JTextField();
        tmotif = new javax.swing.JTextField();
        lnom = new javax.swing.JLabel();
        lmatricule = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        limage = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tprenom = new javax.swing.JTextField();
        tnom = new javax.swing.JTextField();
        lfond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 180, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setText("Taille (m) * :");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel29.setText("Poids (kg)  * :");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel30.setText("Fréquence cardiaque * :");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel31.setText("Températur (C°)  * :");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        tpoids.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tpoids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpoidsActionPerformed(evt);
            }
        });
        jPanel2.add(tpoids, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 90, -1));

        ttaille.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ttaille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttailleActionPerformed(evt);
            }
        });
        jPanel2.add(ttaille, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 90, -1));

        ttempérature.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ttempérature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttempératureActionPerformed(evt);
            }
        });
        jPanel2.add(ttempérature, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 90, -1));

        tfrequence.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfrequence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfrequenceActionPerformed(evt);
            }
        });
        jPanel2.add(tfrequence, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 90, -1));

        tpression.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tpression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpressionActionPerformed(evt);
            }
        });
        jPanel2.add(tpression, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 90, -1));

        bajouter.setBackground(new java.awt.Color(0, 204, 204));
        bajouter.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/verifier.png"))); // NOI18N
        bajouter.setText("Valider");
        bajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajouterActionPerformed(evt);
            }
        });
        jPanel2.add(bajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 660, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Observation * :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, -1, -1));

        tobservation.setColumns(20);
        tobservation.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tobservation.setRows(5);
        jScrollPane1.setViewportView(tobservation);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 250, -1));

        bquitter.setBackground(new java.awt.Color(255, 0, 0));
        bquitter.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bquitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/croix.png"))); // NOI18N
        bquitter.setText("Annuler");
        bquitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bquitterActionPerformed(evt);
            }
        });
        jPanel2.add(bquitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 660, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Antécédents personnels :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Antécédents familiaux :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Antécédents médicaux :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Antécédents chirurgicaux");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        tantpersonnels.setEditable(false);
        tantpersonnels.setColumns(20);
        tantpersonnels.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tantpersonnels.setRows(5);
        jScrollPane3.setViewportView(tantpersonnels);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 260, -1));

        tantfamiliaux.setEditable(false);
        tantfamiliaux.setColumns(20);
        tantfamiliaux.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tantfamiliaux.setRows(5);
        jScrollPane4.setViewportView(tantfamiliaux);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 260, -1));

        tantmedicaux.setEditable(false);
        tantmedicaux.setColumns(20);
        tantmedicaux.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tantmedicaux.setRows(5);
        jScrollPane5.setViewportView(tantmedicaux);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 260, -1));

        tantchirurgicaux.setEditable(false);
        tantchirurgicaux.setColumns(20);
        tantchirurgicaux.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tantchirurgicaux.setRows(5);
        jScrollPane6.setViewportView(tantchirurgicaux);

        jPanel2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 260, -1));

        tglycemie.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tglycemie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglycemieActionPerformed(evt);
            }
        });
        jPanel2.add(tglycemie, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 90, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Pression Artérielle * :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Glycémie * :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, -1));

        bimc.setBackground(new java.awt.Color(0, 255, 255));
        bimc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bimc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IMC - copie.png"))); // NOI18N
        bimc.setText("Calculer IMC");
        bimc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bimcActionPerformed(evt);
            }
        });
        jPanel2.add(bimc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 240, 30));

        tdecision.setEditable(false);
        tdecision.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel2.add(tdecision, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 120, -1));

        timc.setEditable(false);
        timc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel2.add(timc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 120, -1));

        tmotif.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel2.add(tmotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 180, -1));

        lnom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lnom.setText("....");
        jPanel2.add(lnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        lmatricule.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lmatricule.setText(".............");
        jPanel2.add(lmatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jPanel3.setBackground(new java.awt.Color(227, 226, 226));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(limage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 70));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 70));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("Date * :");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("Motif * :");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel32.setText("Prénom Médecin * :");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel33.setText("Nom Médecin * :");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        tprenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tprenomActionPerformed(evt);
            }
        });
        jPanel3.add(tprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 180, -1));

        tnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnomActionPerformed(evt);
            }
        });
        jPanel3.add(tnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 180, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 90));

        lfond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Consultation.png"))); // NOI18N
        jPanel2.add(lfond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tpoidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpoidsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpoidsActionPerformed

    private void ttailleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttailleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttailleActionPerformed

    private void ttempératureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttempératureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttempératureActionPerformed

    private void tfrequenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfrequenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfrequenceActionPerformed

    private void tpressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpressionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpressionActionPerformed

    private void tglycemieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglycemieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglycemieActionPerformed

    private void bajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajouterActionPerformed
        if (tnom.getText().isEmpty()|| tprenom.getText().isEmpty() || jdate.getDate() == null || tmotif.getText().isEmpty()
                || ttaille.getText().isEmpty() || tpoids.getText().isEmpty() || ttempérature.getText().isEmpty() || tfrequence.getText().isEmpty()
                || tglycemie.getText().isEmpty() || tpression.getText().isEmpty() || timc.getText().isEmpty() || tdecision.getText().isEmpty()
                || tobservation.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner tout les champs");
        } else {
            try {
                String idmed = "";
                ps = c.connexionBdd().prepareStatement("select nom_utilisateur from utilisateurs where nom=? and prénom=? and type_utilisateur='Médecin' ");
                ps.setString(1,tnom.getText());
                ps.setString(2, tprenom.getText());
                rs = ps.executeQuery();
                while (rs.next()) {
                    idmed = rs.getString("nom_utilisateur");
                }
                if (idmed.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Médecin n'existe pas !!");
                } else {
                    ps = c.connexionBdd().prepareStatement("insert into consultation(matricule_pat,medecin_id,date_cons,motif,taille,poids,température,fréquence_cardiaque,glycémie,pression_artérielle,imc,imcdec,observation) values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
                    ps.setString(1, lmatricule.getText());
                    ps.setString(2, idmed);
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    String date = sdf.format(jdate.getDate());
                    ps.setString(3, date);
                    ps.setString(4, tmotif.getText());
                    ps.setString(5, ttaille.getText());
                    ps.setString(6, tpoids.getText());
                    ps.setString(7, ttempérature.getText());
                    ps.setString(8, tfrequence.getText());
                    ps.setString(9, tglycemie.getText());
                    ps.setString(10, tpression.getText());
                    ps.setString(11, timc.getText());
                    ps.setString(12, tdecision.getText());
                    ps.setString(13, tobservation.getText());
                    ps.executeUpdate();

                    ps0 = c.connexionBdd().prepareStatement("select consultation_id from consultation");
                    rs = ps0.executeQuery();
                    String id = "";
                    while (rs.next()) {
                        id = rs.getString("consultation_id");
                    }
                    if (authentification.ctype.getSelectedItem().equals("Admin")) {
                        ps1 = c.connexionBdd().prepareStatement("insert into facture(matricule_pat,consultation_id) values(?,?)");

                    }
                    if (authentification.ctype.getSelectedItem().equals("Secrétaire")) {
                        ps1 = c.connexionBdd().prepareStatement("insert into facture(matricule_pat,consultation_id,secretaire_id) values(?,?,?)");
                    }
                    ps1.setString(1, lmatricule.getText());
                    ps1.setString(2, id);
                    if (authentification.ctype.getSelectedItem().equals("Secrétaire")) {
                        ps1.setString(3, authentification.tusername.getText());
                    }

                    ps1.executeUpdate();
                    JOptionPane.showMessageDialog(this, "la consultation a été ajouter avec succés");
                    DetailsPatient.actualiserc();
                    DetailsPatient.actualiserfac();
                    dispose();
                }

            } catch (SQLException ex) {
                Logger.getLogger(DetailsConsultation.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bajouterActionPerformed

    private void bquitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bquitterActionPerformed
        dispose();
    }//GEN-LAST:event_bquitterActionPerformed

    private void bimcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bimcActionPerformed
        if (ttaille.getText().isEmpty() || tpoids.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez saisir la taille et le poids d'abord !!");
        } else {
            timc.setText(CalculerIMC.calcul(Float.parseFloat(ttaille.getText()), Float.parseFloat(tpoids.getText())) + "");
            tdecision.setText(CalculerIMC.typeIMC(Float.parseFloat(timc.getText())));
        }
    }//GEN-LAST:event_bimcActionPerformed

    private void tprenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tprenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tprenomActionPerformed

    private void tnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailsConsultation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bajouter;
    private javax.swing.JButton bimc;
    private javax.swing.JButton bquitter;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JLabel lfond;
    private javax.swing.JLabel limage;
    private javax.swing.JLabel lmatricule;
    private javax.swing.JLabel lnom;
    private javax.swing.JTextArea tantchirurgicaux;
    private javax.swing.JTextArea tantfamiliaux;
    private javax.swing.JTextArea tantmedicaux;
    private javax.swing.JTextArea tantpersonnels;
    private javax.swing.JTextField tdecision;
    private javax.swing.JTextField tfrequence;
    private javax.swing.JTextField tglycemie;
    private javax.swing.JTextField timc;
    private javax.swing.JTextField tmotif;
    private javax.swing.JTextField tnom;
    private javax.swing.JTextArea tobservation;
    private javax.swing.JTextField tpath;
    private javax.swing.JTextField tpoids;
    private javax.swing.JTextField tprenom;
    private javax.swing.JTextField tpression;
    private javax.swing.JTextField ttaille;
    private javax.swing.JTextField ttempérature;
    // End of variables declaration//GEN-END:variables
}
