/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Controleur.*;
import Modele.*;
import java.awt.Image;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author azus
 */
public class DétailsConsultationMedVoir extends javax.swing.JFrame {

    Connexion c = new Connexion();
    PreparedStatement ps, ps1;
    DefaultTableModel dft = new DefaultTableModel();
    ResultSet rs;

    /**
     * Creates new form DétailsConsultationMedVoir
     */
    public DétailsConsultationMedVoir() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        try {
            ps = c.connexionBdd().prepareStatement("select * from patient where matricule_pat=?");
            ps.setString(1, PageConsultations.tconsultation.getValueAt(PageConsultations.tconsultation.getSelectedRow(), 3) + "");
            rs = ps.executeQuery();
            while (rs.next()) {
                lmatricule.setText(rs.getString("matricule_pat"));
                lnom.setText(rs.getString("nom_pat") + " " + rs.getString("prénom_pat"));
                tantchirurgicaux.setText(rs.getString("antécédents_chirurgicaux"));
                tantfamiliaux.setText(rs.getString("antécédents_familiaux"));
                tantmedicaux.setText(rs.getString("antécédents_médicaux"));
                tantpersonnels.setText(rs.getString("antécédents_personnels"));
                byte[] photo = rs.getBytes("photo_patient");
                ImageIcon imgic = new ImageIcon(photo);
                Image img = imgic.getImage().getScaledInstance(limage.getWidth(), limage.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imgf = new ImageIcon(img);
                limage.setIcon(imgf);
                tpath.setText(rs.getString("tpath"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DetailsConsultationMAJ.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            ps = c.connexionBdd().prepareStatement("select * from consultation where consultation_id=?");
            ps.setString(1, PageConsultations.tconsultation.getValueAt(PageConsultations.tconsultation.getSelectedRow(), 0) + "");
            rs = ps.executeQuery();
            while (rs.next()) {
                lnumcons.setText(rs.getString("consultation_id"));
                jdate.setText(rs.getDate("date_cons") + "");
                tmotif.setText(rs.getString("motif"));
                tpoids.setText(rs.getString("poids"));
                ttaille.setText(rs.getString("taille"));
                ttempérature.setText(rs.getString("température"));
                tfrequence.setText(rs.getString("fréquence_cardiaque"));
                tglycemie.setText(rs.getString("glycémie"));
                tpression.setText(rs.getString("pression_artérielle"));
                timc.setText(rs.getString("imc"));
                tdecision.setText(rs.getString("imcdec"));
                tobservation.setText(rs.getString("observation"));
                tresultat.setText(rs.getString("résultat_cons"));
                tdiagnostique.setText(rs.getString("diagnostique"));
                tmontant.setText(rs.getString("prix_consultation"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DetailsConsultationMAJ.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpath = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tresultat = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tdiagnostique = new javax.swing.JTextArea();
        tmontant = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        limage = new javax.swing.JLabel();
        lnom = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tpoids = new javax.swing.JTextField();
        ttaille = new javax.swing.JTextField();
        ttempérature = new javax.swing.JTextField();
        tfrequence = new javax.swing.JTextField();
        tpression = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tobservation = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tantpersonnels = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        tantfamiliaux = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        tantmedicaux = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        tantchirurgicaux = new javax.swing.JTextArea();
        tglycemie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bimc = new javax.swing.JButton();
        tdecision = new javax.swing.JTextField();
        timc = new javax.swing.JTextField();
        lmatricule = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lnumcons = new javax.swing.JLabel();
        bannuler = new javax.swing.JButton();
        bimprimer = new javax.swing.JButton();
        bimprimerFacture = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jdate = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tmotif = new javax.swing.JTextField();
        lfond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel34.setText("Diagnostique médical :");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, -1, -1));

        tresultat.setEditable(false);
        tresultat.setColumns(20);
        tresultat.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tresultat.setRows(5);
        jScrollPane1.setViewportView(tresultat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 300, -1));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel35.setText("Résultat de l'examen :");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Montant :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, -1, -1));

        tdiagnostique.setEditable(false);
        tdiagnostique.setColumns(20);
        tdiagnostique.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tdiagnostique.setRows(5);
        jScrollPane2.setViewportView(tdiagnostique);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 300, -1));

        tmontant.setEditable(false);
        tmontant.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(tmontant, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 300, 30));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(limage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 60));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 60));

        lnom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lnom.setText("....");
        getContentPane().add(lnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setText("Taille (m) :");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel29.setText("Poids (kg) :");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel30.setText("Fréquence cardiaque :");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel31.setText("Températur (C°) :");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        tpoids.setEditable(false);
        tpoids.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tpoids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpoidsActionPerformed(evt);
            }
        });
        getContentPane().add(tpoids, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 110, -1));

        ttaille.setEditable(false);
        ttaille.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ttaille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttailleActionPerformed(evt);
            }
        });
        getContentPane().add(ttaille, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 110, -1));

        ttempérature.setEditable(false);
        ttempérature.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ttempérature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttempératureActionPerformed(evt);
            }
        });
        getContentPane().add(ttempérature, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 110, -1));

        tfrequence.setEditable(false);
        tfrequence.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfrequence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfrequenceActionPerformed(evt);
            }
        });
        getContentPane().add(tfrequence, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 110, -1));

        tpression.setEditable(false);
        tpression.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tpression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpressionActionPerformed(evt);
            }
        });
        getContentPane().add(tpression, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 110, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Observation :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, -1, -1));

        tobservation.setEditable(false);
        tobservation.setColumns(20);
        tobservation.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tobservation.setRows(5);
        jScrollPane7.setViewportView(tobservation);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 250, 110));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Antécédents personnels :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Antécédents familiaux :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Antécédents médicaux :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Antécédents chirurgicaux");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        tantpersonnels.setEditable(false);
        tantpersonnels.setColumns(20);
        tantpersonnels.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tantpersonnels.setRows(5);
        jScrollPane3.setViewportView(tantpersonnels);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 260, -1));

        tantfamiliaux.setEditable(false);
        tantfamiliaux.setColumns(20);
        tantfamiliaux.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tantfamiliaux.setRows(5);
        jScrollPane4.setViewportView(tantfamiliaux);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 260, -1));

        tantmedicaux.setEditable(false);
        tantmedicaux.setColumns(20);
        tantmedicaux.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tantmedicaux.setRows(5);
        jScrollPane5.setViewportView(tantmedicaux);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 260, -1));

        tantchirurgicaux.setEditable(false);
        tantchirurgicaux.setColumns(20);
        tantchirurgicaux.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tantchirurgicaux.setRows(5);
        jScrollPane6.setViewportView(tantchirurgicaux);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 260, -1));

        tglycemie.setEditable(false);
        tglycemie.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tglycemie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglycemieActionPerformed(evt);
            }
        });
        getContentPane().add(tglycemie, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 110, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Pression Artérielle :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Glycémie :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        bimc.setBackground(new java.awt.Color(0, 255, 255));
        bimc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bimc.setText("Calculer IMC");
        bimc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bimcActionPerformed(evt);
            }
        });
        getContentPane().add(bimc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 230, 30));

        tdecision.setEditable(false);
        tdecision.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(tdecision, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 120, -1));

        timc.setEditable(false);
        timc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(timc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 110, -1));

        lmatricule.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lmatricule.setText(".............");
        getContentPane().add(lmatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("N° Consultation :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        lnumcons.setText("...");
        getContentPane().add(lnumcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        bannuler.setBackground(new java.awt.Color(255, 0, 0));
        bannuler.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bannuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/croix.png"))); // NOI18N
        bannuler.setText("Annuler");
        bannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bannulerActionPerformed(evt);
            }
        });
        getContentPane().add(bannuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 660, -1, -1));

        bimprimer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bimprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imprimante.png"))); // NOI18N
        bimprimer.setText("Imprimer");
        bimprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bimprimerActionPerformed(evt);
            }
        });
        getContentPane().add(bimprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 660, -1, -1));

        bimprimerFacture.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bimprimerFacture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imprimante_1.png"))); // NOI18N
        bimprimerFacture.setText("Facture");
        bimprimerFacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bimprimerFactureActionPerformed(evt);
            }
        });
        getContentPane().add(bimprimerFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 660, 100, 30));

        jPanel3.setBackground(new java.awt.Color(227, 226, 226));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("Date :");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        jdate.setEditable(false);
        jPanel3.add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 150, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("Motif :");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, -1, -1));

        tmotif.setEditable(false);
        tmotif.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel3.add(tmotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 150, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 90));

        lfond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Consultation.png"))); // NOI18N
        getContentPane().add(lfond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tpoidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpoidsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpoidsActionPerformed

    private void ttailleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttailleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttailleActionPerformed

    private void ttempératureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttempératureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttempératureActionPerformed

    private void tfrequenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfrequenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfrequenceActionPerformed

    private void tpressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpressionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpressionActionPerformed

    private void tglycemieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglycemieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglycemieActionPerformed

    private void bimcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bimcActionPerformed

    }//GEN-LAST:event_bimcActionPerformed

    private void bannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bannulerActionPerformed
        dispose();
    }//GEN-LAST:event_bannulerActionPerformed

    private void bimprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bimprimerActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_cabinet_medical", "root", "");
            JasperDesign jdesing = JRXmlLoader.load("C:\\Users\\azus\\Documents\\NetBeansProjects\\gestion d'une cabinet medicale V7\\src\\EtatImpression\\FicheConsultation.jrxml");
            String query = "select consultation.*, utilisateurs.nom,utilisateurs.prénom from consultation,utilisateurs where consultation.medecin_id=utilisateurs.nom_utilisateur and consultation_id='" + lnumcons.getText() + "'";
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(query);
            jdesing.setQuery(updateQuery);
            JasperReport jreport = JasperCompileManager.compileReport(jdesing);
            JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);

            JasperViewer.viewReport(jprint);

        } catch (ClassNotFoundException | SQLException | JRException ex) {
            Logger.getLogger(DetailsPatient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bimprimerActionPerformed

    private void bimprimerFactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bimprimerFactureActionPerformed
        if (Médecin.prv.charAt(31) == '1') {
        try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_cabinet_medical", "root", "");
                JasperDesign jdesing = JRXmlLoader.load("C:\\Users\\azus\\Documents\\NetBeansProjects\\gestion d'une cabinet medicale V7\\src\\EtatImpression\\Facture.jrxml");
                String query = "select facture.* , patient.nom_pat,patient.prénom_pat from patient, facture where patient.matricule_pat= facture.matricule_pat and consultation_id='" + lnumcons.getText() + "'";
                JRDesignQuery updateQuery = new JRDesignQuery();
                updateQuery.setText(query);
                jdesing.setQuery(updateQuery);
                JasperReport jreport = JasperCompileManager.compileReport(jdesing);
                JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);

                JasperViewer.viewReport(jprint);

            } catch (ClassNotFoundException | SQLException | JRException ex) {
                Logger.getLogger(DétailsConsultationMedVoir.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }
    }//GEN-LAST:event_bimprimerFactureActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DétailsConsultationMedVoir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DétailsConsultationMedVoir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DétailsConsultationMedVoir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DétailsConsultationMedVoir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DétailsConsultationMedVoir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bannuler;
    private javax.swing.JButton bimc;
    private javax.swing.JButton bimprimer;
    private javax.swing.JButton bimprimerFacture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jdate;
    private javax.swing.JLabel lfond;
    private javax.swing.JLabel limage;
    private javax.swing.JLabel lmatricule;
    private javax.swing.JLabel lnom;
    private javax.swing.JLabel lnumcons;
    private javax.swing.JTextArea tantchirurgicaux;
    private javax.swing.JTextArea tantfamiliaux;
    private javax.swing.JTextArea tantmedicaux;
    private javax.swing.JTextArea tantpersonnels;
    private javax.swing.JTextField tdecision;
    private javax.swing.JTextArea tdiagnostique;
    private javax.swing.JTextField tfrequence;
    private javax.swing.JTextField tglycemie;
    private javax.swing.JTextField timc;
    private javax.swing.JTextField tmontant;
    private javax.swing.JTextField tmotif;
    private javax.swing.JTextArea tobservation;
    private javax.swing.JLabel tpath;
    private javax.swing.JTextField tpoids;
    private javax.swing.JTextField tpression;
    private javax.swing.JTextArea tresultat;
    private javax.swing.JTextField ttaille;
    private javax.swing.JTextField ttempérature;
    // End of variables declaration//GEN-END:variables
}
