/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.Connexion;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author azus
 */
public class FactureDétails extends javax.swing.JFrame {

    Connexion c = new Connexion();
    PreparedStatement ps, ps1;
    DefaultTableModel dft = new DefaultTableModel();
    ResultSet rs, rs1;

    /**
     * Creates new form FactureDétails
     */
    public FactureDétails() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        try {
            tnumfac.setText(DetailsPatient.tfacture.getValueAt(DetailsPatient.tfacture.getSelectedRow(), 0)+"");
            ps = c.connexionBdd().prepareStatement("select * from patient where matricule_pat=?");
            ps.setString(1, DetailsPatient.tmatricule.getText());
            rs = ps.executeQuery();
            while (rs.next()) {
                lmatricule.setText(rs.getString("matricule_pat"));
                lnom.setText(rs.getString("nom_pat") + " " + rs.getString("prénom_pat"));
                byte[] photo = rs.getBytes("photo_patient");
                ImageIcon imgic = new ImageIcon(photo);
                Image img = imgic.getImage().getScaledInstance(limage.getWidth(), limage.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imgf = new ImageIcon(img);
                limage.setIcon(imgf);
                tpath.setText(rs.getString("tpath"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FactureDétails.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ps = c.connexionBdd().prepareStatement("select * from facture where facture_id=?");
            ps.setString(1,tnumfac.getText());
            rs = ps.executeQuery();
            while (rs.next()) {
                jdate.setText(rs.getString("date_versement"));
                tdescription.setText(rs.getString("descriprion_versement"));
                tmontantverse.setText(rs.getString("montant_versé"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FactureDétails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpath = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tmontantverse = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdescription = new javax.swing.JTextArea();
        jdate = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        limage = new javax.swing.JLabel();
        lnom = new javax.swing.JLabel();
        lmatricule = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tnumfac = new javax.swing.JLabel();
        bimprimer = new javax.swing.JButton();
        bannuler = new javax.swing.JButton();

        tpath.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Date versement * :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Montant versé * :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("description de versement :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        tmontantverse.setEditable(false);
        tmontantverse.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tmontantverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmontantverseActionPerformed(evt);
            }
        });
        getContentPane().add(tmontantverse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 180, -1));

        tdescription.setEditable(false);
        tdescription.setColumns(20);
        tdescription.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tdescription.setRows(5);
        jScrollPane1.setViewportView(tdescription);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jdate.setEditable(false);
        jdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdateActionPerformed(evt);
            }
        });
        getContentPane().add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(limage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 60));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 60));

        lnom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lnom.setText("....");
        getContentPane().add(lnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        lmatricule.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lmatricule.setText(".............");
        getContentPane().add(lmatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("N° Facture :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        tnumfac.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tnumfac.setText("...");
        getContentPane().add(tnumfac, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        bimprimer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bimprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imprimante.png"))); // NOI18N
        bimprimer.setText("Imprimer");
        bimprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bimprimerActionPerformed(evt);
            }
        });
        getContentPane().add(bimprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        bannuler.setBackground(new java.awt.Color(255, 0, 0));
        bannuler.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bannuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/croix.png"))); // NOI18N
        bannuler.setText("Annuler");
        bannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bannulerActionPerformed(evt);
            }
        });
        getContentPane().add(bannuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tmontantverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmontantverseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmontantverseActionPerformed

    private void jdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdateActionPerformed

    private void bimprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bimprimerActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_cabinet_medical", "root", "");
            JasperDesign jdesing = JRXmlLoader.load("C:\\Users\\azus\\Documents\\NetBeansProjects\\gestion d'une cabinet medicale V7\\src\\EtatImpression\\Règlement.jrxml");
            String query = "select facture.* , patient.nom_pat,patient.prénom_pat from patient, facture where patient.matricule_pat= facture.matricule_pat and facture_id='" + tnumfac.getText() + "'";
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(query);
            jdesing.setQuery(updateQuery);
            JasperReport jreport = JasperCompileManager.compileReport(jdesing);
            JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);

            JasperViewer.viewReport(jprint);

        } catch (ClassNotFoundException | SQLException | JRException ex) {
            Logger.getLogger(DetailsPatient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bimprimerActionPerformed

    private void bannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bannulerActionPerformed
        dispose();
    }//GEN-LAST:event_bannulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FactureDétails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FactureDétails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FactureDétails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FactureDétails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FactureDétails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bannuler;
    private javax.swing.JButton bimprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jdate;
    private javax.swing.JLabel limage;
    private javax.swing.JLabel lmatricule;
    private javax.swing.JLabel lnom;
    private javax.swing.JTextArea tdescription;
    private javax.swing.JTextField tmontantverse;
    private javax.swing.JLabel tnumfac;
    private javax.swing.JLabel tpath;
    // End of variables declaration//GEN-END:variables
}
