/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.*;
import Vue.PageAide;
import Vue.PageNotes;
import Vue.PageConsultations;
import Vue.PagePlanning;
import Vue.PageSalleDattente;
import Vue.PageStat;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author azus
 */
public class Médecin extends javax.swing.JFrame {

    /**
     * Creates new form AcceuilMedecin
     */
    Connexion c = new Connexion();
    PreparedStatement ps;
    ResultSet rs;
    public static String prv = "";

    public Médecin() {
        initComponents();
        //setLocationRelativeTo(this);
        try {
            ps = c.connexionBdd().prepareStatement("select privilége from utilisateurs where nom_utilisateur=?");
            ps.setString(1, authentification.tusername.getText());
            rs = ps.executeQuery();
            while (rs.next()) {
                prv = rs.getString("privilége");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Médecin.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMéd = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelSalle = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelSalle1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabelPlanning = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabelStat = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabelNotes = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel_Acceuil = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabelAide = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelPage = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel1PropertyChange(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 33)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Médecin");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 330, 40));

        jLabelMéd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMéd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/doct.png"))); // NOI18N
        jPanel1.add(jLabelMéd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 120));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/separateur.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 330, 10));

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        jLabelSalle.setBackground(new java.awt.Color(0, 0, 204));
        jLabelSalle.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabelSalle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelSalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salle d'attente.png"))); // NOI18N
        jLabelSalle.setText("   Salle d'attente");
        jLabelSalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSalleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSalleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSalle, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 330, 80));

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        jLabelSalle1.setBackground(new java.awt.Color(0, 0, 204));
        jLabelSalle1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabelSalle1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelSalle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/patient(1).png"))); // NOI18N
        jLabelSalle1.setText("   Consultations");
        jLabelSalle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalle1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSalle1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSalle1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSalle1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSalle1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 330, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 204));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });

        jLabelPlanning.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabelPlanning.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPlanning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/planning.png"))); // NOI18N
        jLabelPlanning.setText("      Planning");
        jLabelPlanning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPlanningMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelPlanningMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPlanningMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPlanning, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPlanning, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 330, -1));

        jPanel8.setBackground(new java.awt.Color(0, 0, 204));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
        });

        jLabelStat.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabelStat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelStat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/statistique.png"))); // NOI18N
        jLabelStat.setText("    Statistiques");
        jLabelStat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelStatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelStatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelStatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStat, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelStat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 330, 80));

        jPanel9.setBackground(new java.awt.Color(0, 0, 204));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });

        jLabelNotes.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabelNotes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/notes - copie.png"))); // NOI18N
        jLabelNotes.setText("        Notes");
        jLabelNotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNotesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelNotesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelNotesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNotes, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNotes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 330, -1));

        jPanel6.setBackground(new java.awt.Color(0, 0, 204));
        jPanel6.setToolTipText("");
        jPanel6.setName(""); // NOI18N
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel_Acceuil.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel_Acceuil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Acceuil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/acceuil.png"))); // NOI18N
        jLabel_Acceuil.setText("       Acceuil");
        jLabel_Acceuil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_AcceuilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_AcceuilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_AcceuilMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_AcceuilMousePressed(evt);
            }
        });
        jLabel_Acceuil.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel_AcceuilPropertyChange(evt);
            }
        });
        jPanel6.add(jLabel_Acceuil, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 330, 80));

        jPanel12.setBackground(new java.awt.Color(0, 0, 204));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel12MouseExited(evt);
            }
        });

        jLabelAide.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabelAide.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelAide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aide.png"))); // NOI18N
        jLabelAide.setText("         Aide");
        jLabelAide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAideMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAideMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAide, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAide, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 330, -1));

        jPanel11.setBackground(new java.awt.Color(0, 0, 204));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel11MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/se-deconnecter.png"))); // NOI18N
        jLabel1.setText("   Déconnexion");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 330, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 960));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanelPage.setBackground(java.awt.Color.white);
        jPanelPage.setPreferredSize(new java.awt.Dimension(1208, 911));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/heart.gif"))); // NOI18N

        javax.swing.GroupLayout jPanelPageLayout = new javax.swing.GroupLayout(jPanelPage);
        jPanelPage.setLayout(jPanelPageLayout);
        jPanelPageLayout.setHorizontalGroup(
            jPanelPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPageLayout.createSequentialGroup()
                .addContainerGap(610, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(486, 486, 486))
        );
        jPanelPageLayout.setVerticalGroup(
            jPanelPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPageLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(507, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setText("Heure : ");

        jLabel6.setText("Compte : Type ");

        jLabel7.setText("Date : ");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ampoule.png"))); // NOI18N

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/avatar-homme.png"))); // NOI18N

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/connecté.png"))); // NOI18N
        jLabel15.setText("Connecté");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGO.png"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addComponent(jLabel9)
                .addGap(136, 136, 136)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 1207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelPage, javax.swing.GroupLayout.PREFERRED_SIZE, 1216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelPage, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 1230, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_AcceuilPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel_AcceuilPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_AcceuilPropertyChange

    private void jLabel_AcceuilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AcceuilMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel_AcceuilMouseClicked

    private void jLabel_AcceuilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AcceuilMousePressed
        PageAcceuil acceuil;
        acceuil = new PageAcceuil();
        jPanelPage.removeAll();
        jPanelPage.add(acceuil).setVisible(true);
    }//GEN-LAST:event_jLabel_AcceuilMousePressed

    private void jLabel_AcceuilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AcceuilMouseEntered
        jPanel6.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_jLabel_AcceuilMouseEntered

    private void jLabel_AcceuilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AcceuilMouseExited
        jPanel6.setBackground(null);
    }//GEN-LAST:event_jLabel_AcceuilMouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        jPanel6.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        // TODO add your handling code here:
        jPanel6.setBackground(null);
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        jPanel5.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jLabelSalleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalleMouseEntered
        jPanel4.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_jLabelSalleMouseEntered

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        jPanel4.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jLabelPlanningMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPlanningMouseEntered
        jPanel7.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_jLabelPlanningMouseEntered

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        jPanel7.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jLabelStatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStatMouseEntered
        jPanel8.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_jLabelStatMouseEntered

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
        jPanel8.setBackground(null);
    }//GEN-LAST:event_jPanel8MouseExited

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        jPanel8.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        jPanel9.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jLabelAideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAideMouseEntered
        jPanel12.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_jLabelAideMouseEntered

    private void jLabelSalleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalleMouseExited
        jPanel4.setBackground(null);
    }//GEN-LAST:event_jLabelSalleMouseExited

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        jPanel5.setBackground(null);
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        jPanel4.setBackground(null);
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        jPanel7.setBackground(null);
    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        jPanel9.setBackground(null);
    }//GEN-LAST:event_jPanel9MouseExited

    private void jLabelAideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAideMouseExited
        jPanel12.setBackground(null);
    }//GEN-LAST:event_jLabelAideMouseExited

    private void jLabelStatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStatMouseExited
        jPanel8.setBackground(null);
    }//GEN-LAST:event_jLabelStatMouseExited

    private void jLabelPlanningMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPlanningMouseExited
        jPanel7.setBackground(null);
    }//GEN-LAST:event_jLabelPlanningMouseExited

    private void jPanel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel1PropertyChange

    }//GEN-LAST:event_jPanel1PropertyChange

    private void jLabelSalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalleMouseClicked
        PageSalleDattente salledattente;
        salledattente = new PageSalleDattente();
        jPanelPage.removeAll();
        jPanelPage.add(salledattente).setVisible(true);
    }//GEN-LAST:event_jLabelSalleMouseClicked

    private void jLabelPlanningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPlanningMouseClicked
        PagePlanning planning = new PagePlanning();
        jPanelPage.removeAll();
        jPanelPage.add(planning).setVisible(true);
    }//GEN-LAST:event_jLabelPlanningMouseClicked

    private void jLabelStatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStatMouseClicked
        PageStat stat = new PageStat();
        jPanelPage.removeAll();
        jPanelPage.add(stat).setVisible(true);
    }//GEN-LAST:event_jLabelStatMouseClicked

    private void jLabelAideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAideMouseClicked
        // TODO add your handling code here:
        PageAide aide = new PageAide();
        jPanelPage.removeAll();
        jPanelPage.add(aide).setVisible(true);
    }//GEN-LAST:event_jLabelAideMouseClicked

    private void jLabelSalle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalle1MouseClicked
        PageConsultations sallepatients = new PageConsultations();
        jPanelPage.removeAll();
        jPanelPage.add(sallepatients).setVisible(true);
    }//GEN-LAST:event_jLabelSalle1MouseClicked

    private void jLabelSalle1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalle1MouseEntered
        jPanel3.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_jLabelSalle1MouseEntered

    private void jLabelSalle1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalle1MouseExited
        jPanel3.setBackground(null);
    }//GEN-LAST:event_jLabelSalle1MouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        jPanel3.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        jPanel3.setBackground(null);
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        PageConsultations sallepatients;
        sallepatients = new PageConsultations();
        jPanelPage.removeAll();
        jPanelPage.add(sallepatients).setVisible(true);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        PageSalleDattente salledattente;
        salledattente = new PageSalleDattente();
        jPanelPage.removeAll();
        jPanelPage.add(salledattente).setVisible(true);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        PagePlanning planning = new PagePlanning();
        jPanelPage.removeAll();
        jPanelPage.add(planning).setVisible(true);
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        PageStat stat = new PageStat();
        jPanelPage.removeAll();
        jPanelPage.add(stat).setVisible(true);
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        PageNotes notes = new PageNotes();
        jPanelPage.removeAll();
        jPanelPage.add(notes).setVisible(true);
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jLabelNotesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNotesMouseExited
        jPanel9.setBackground(null);
    }//GEN-LAST:event_jLabelNotesMouseExited

    private void jLabelNotesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNotesMouseEntered
        jPanel9.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_jLabelNotesMouseEntered

    private void jLabelNotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNotesMouseClicked
        PageNotes notes = new PageNotes();
        jPanelPage.removeAll();
        jPanelPage.add(notes).setVisible(true);
    }//GEN-LAST:event_jLabelNotesMouseClicked

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        PageAide aide = new PageAide();
        jPanelPage.removeAll();
        jPanelPage.add(aide).setVisible(true);
    }//GEN-LAST:event_jPanel12MouseClicked

    private void jPanel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseEntered
        jPanel12.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_jPanel12MouseEntered

    private void jPanel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseExited
        jPanel12.setBackground(null);
    }//GEN-LAST:event_jPanel12MouseExited

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jPanel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseEntered
        jPanel11.setBackground(new java.awt.Color(174, 214, 241));
    }//GEN-LAST:event_jPanel11MouseEntered

    private void jPanel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseExited
        jPanel11.setBackground(null);
    }//GEN-LAST:event_jPanel11MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Médecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Médecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Médecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Médecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Médecin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAide;
    private javax.swing.JLabel jLabelMéd;
    private javax.swing.JLabel jLabelNotes;
    private javax.swing.JLabel jLabelPlanning;
    private javax.swing.JLabel jLabelSalle;
    private javax.swing.JLabel jLabelSalle1;
    private javax.swing.JLabel jLabelStat;
    private javax.swing.JLabel jLabel_Acceuil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public static javax.swing.JPanel jPanelPage;
    // End of variables declaration//GEN-END:variables
}
