/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.Connexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author azus
 */
public class NoteMAJ extends javax.swing.JFrame {

    Connexion c = new Connexion();
    PreparedStatement ps;
    DefaultTableModel dft = new DefaultTableModel();
    ResultSet rs;

    /**
     * Creates new form NoteMAJ
     */
    public NoteMAJ() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        try {
            ps = c.connexionBdd().prepareStatement("select * from notes where note_id=?");
            ps.setString(1, PageNotes.tnotes.getValueAt(PageNotes.tnotes.getSelectedRow(), 0)+"");
            rs = ps.executeQuery();
            while (rs.next()) {
                tnote.setText(rs.getString("contenue"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(NoteMAJ.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tnote = new javax.swing.JTextArea();
        benregistrer = new javax.swing.JButton();
        bquitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ecrivez votre note ici :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 255));

        tnote.setColumns(20);
        tnote.setRows(5);
        jScrollPane1.setViewportView(tnote);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 720, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 740, 420));

        benregistrer.setBackground(new java.awt.Color(0, 204, 204));
        benregistrer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        benregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/verifier.png"))); // NOI18N
        benregistrer.setText("Enregistrer");
        benregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benregistrerActionPerformed(evt);
            }
        });
        getContentPane().add(benregistrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        bquitter.setBackground(new java.awt.Color(255, 0, 0));
        bquitter.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bquitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/croix.png"))); // NOI18N
        bquitter.setText("Annuler");
        bquitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bquitterActionPerformed(evt);
            }
        });
        getContentPane().add(bquitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void benregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benregistrerActionPerformed
        if (tnote.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "La note est vide !");
        }
        if (JOptionPane.showConfirmDialog(this, "Voullez vous vraiment modifier?",
                "Confirmation de modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                ps = c.connexionBdd().prepareStatement("update notes set contenue=? where note_id=?");
                ps.setString(1, tnote.getText());
                ps.setString(2, PageNotes.tnotes.getValueAt(PageNotes.tnotes.getSelectedRow(), 0)+"");
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Mise a jours faite avec succés");
                PageNotes.actualiser();
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(NoteMAJ.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_benregistrerActionPerformed

    private void bquitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bquitterActionPerformed
        dispose();
    }//GEN-LAST:event_bquitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NoteMAJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NoteMAJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NoteMAJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoteMAJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NoteMAJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton benregistrer;
    private javax.swing.JButton bquitter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tnote;
    // End of variables declaration//GEN-END:variables
}
