/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.*;
import static Vue.DetailsPatient.tmatricule;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author azus
 */
public class OrdonnanceVue extends javax.swing.JFrame {

    Connexion c = new Connexion();
    PreparedStatement ps, ps1;
    DefaultTableModel dft = new DefaultTableModel();
    ResultSet rs;

    /**
     * Creates new form OrdonnanceVue
     */
    public OrdonnanceVue() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        try {
            ps = c.connexionBdd().prepareStatement("select * from patient where matricule_pat=?");
            ps.setString(1, PageConsultations.tconsultation.getValueAt(PageConsultations.tconsultation.getSelectedRow(), 3) + "");
            rs = ps.executeQuery();
            while (rs.next()) {
                lmatricule.setText(rs.getString("matricule_pat"));
                lnom.setText(rs.getString("nom_pat") + " " + rs.getString("prénom_pat"));
                byte[] photo = rs.getBytes("photo_patient");
                ImageIcon imgic = new ImageIcon(photo);
                Image img = imgic.getImage().getScaledInstance(limage.getWidth(), limage.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imgf = new ImageIcon(img);
                limage.setIcon(imgf);
                tpath.setText(rs.getString("tpath"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrdonnanceMAJJ.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            ps = c.connexionBdd().prepareStatement("select * from ordonnance where ordonnance_id=?");
            ps.setString(1, PageConsultations.tordonnance.getValueAt(PageConsultations.tordonnance.getSelectedRow(), 0) + "");
            rs = ps.executeQuery();
            while (rs.next()) {
                lordonance.setText(rs.getString("ordonnance_id"));
                tdure.setText(rs.getString("duré_trait"));
                date.setText(rs.getDate("date_or") + "");
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrdonnanceMAJJ.class.getName()).log(Level.SEVERE, null, ex);
        }

        Actualiser();
    }

    public void Actualiser() {
        dft.setRowCount(0);
        dft.setColumnCount(0);
        try {
            dft.addColumn("ID");
            dft.addColumn("Médicament");
            dft.addColumn("Famille");
            dft.addColumn("Forme");
            dft.addColumn("Dosage");
            dft.addColumn("Posologie");
            dft.addColumn("Quantité");

            ps = c.connexionBdd().prepareStatement("select * from medicament where ordonnance_id= ?");
            ps.setString(1, lordonance.getText());
            rs = ps.executeQuery();
            while (rs.next()) {
                dft.addRow(new Object[]{
                    rs.getString("medicament_id"),
                    rs.getString("nom_med"),
                    rs.getString("famille_med"),
                    rs.getString("forme"),
                    rs.getString("dosage"),
                    rs.getString("posologie_usuelle"),
                    rs.getString("qte_med")
                }
                );
            }
            tmedicament.setModel(dft);
        } catch (SQLException ex) {
            Logger.getLogger(OrdonnanceMAJJ.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpath = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        limage = new javax.swing.JLabel();
        lnom = new javax.swing.JLabel();
        lmatricule = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tmedicament = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bquitter = new javax.swing.JButton();
        tdure = new javax.swing.JTextField();
        tfamille = new javax.swing.JTextField();
        tdosage = new javax.swing.JTextField();
        tquantite = new javax.swing.JTextField();
        tposologie = new javax.swing.JTextField();
        tforme = new javax.swing.JTextField();
        tobservation = new javax.swing.JTextField();
        tnommed = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lordonance = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        bimprimer = new javax.swing.JButton();

        tpath.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Date :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jLabel3.setText("Duré traitement :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(limage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 60));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 60));

        lnom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lnom.setText("....");
        getContentPane().add(lnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        lmatricule.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lmatricule.setText(".............");
        getContentPane().add(lmatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Les Medicaments");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        tmedicament.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Médicament", "Famille", "Forme", "Dosage", "Posologie", "Quantité"
            }
        ));
        tmedicament.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmedicamentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tmedicament);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 680, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 680, 310));

        jLabel5.setText("Dosage :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel6.setText("Posologie usuelle :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel7.setText("Famille :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jLabel8.setText("Forme :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 124, -1, 20));

        jLabel9.setText("Observation :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        jLabel10.setText("Quantité");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel11.setText("Médicament :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        bquitter.setText("Quitter");
        bquitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bquitterActionPerformed(evt);
            }
        });
        getContentPane().add(bquitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, -1, -1));

        tdure.setEditable(false);
        getContentPane().add(tdure, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 150, -1));

        tfamille.setEditable(false);
        getContentPane().add(tfamille, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 110, -1));

        tdosage.setEditable(false);
        getContentPane().add(tdosage, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 120, -1));

        tquantite.setEditable(false);
        getContentPane().add(tquantite, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 120, -1));

        tposologie.setEditable(false);
        getContentPane().add(tposologie, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 110, -1));

        tforme.setEditable(false);
        getContentPane().add(tforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 90, -1));

        tobservation.setEditable(false);
        getContentPane().add(tobservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 90, -1));

        tnommed.setEditable(false);
        getContentPane().add(tnommed, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 120, -1));

        jLabel1.setText("Ordonnance id :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        lordonance.setText("..");
        getContentPane().add(lordonance, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        date.setEditable(false);
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 150, -1));

        bimprimer.setText("Imprimer");
        bimprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bimprimerActionPerformed(evt);
            }
        });
        getContentPane().add(bimprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tmedicamentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmedicamentMouseClicked
        try {
            ps = c.connexionBdd().prepareStatement("select * from medicament where medicament_id=?");
            ps.setString(1, tmedicament.getValueAt(tmedicament.getSelectedRow(), 0) + "");
            rs = ps.executeQuery();
            while (rs.next()) {
                tnommed.setText(rs.getString("nom_med"));
                tfamille.setText(rs.getString("famille_med"));
                tforme.setText(rs.getString("forme"));
                tdosage.setText(rs.getString("dosage"));
                tposologie.setText(rs.getString("posologie_usuelle"));
                tobservation.setText(rs.getString("observation"));
                tquantite.setText(rs.getString("qte_med"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AcceuilComptable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tmedicamentMouseClicked

    private void bquitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bquitterActionPerformed
        dispose();
    }//GEN-LAST:event_bquitterActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void bimprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bimprimerActionPerformed
        if (Médecin.prv.charAt(19) == '1') {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_cabinet_medical", "root", "");
                JasperDesign jdesing = JRXmlLoader.load("C:\\Users\\azus\\Documents\\NetBeansProjects\\gestion d'une cabinet medicale V7\\src\\EtatImpression\\FicheOrdonnance1.jrxml");
                String query = "Select ordonnance.* , medicament.*, utilisateurs.nom as nom ,patient.nom_pat,patient.prénom_pat,patient.date_naissance , medecin.specialite from ordonnance left join medicament on (medicament.ordonnance_id=ordonnance.ordonnance_id) left join patient on (patient.matricule_pat=ordonnance.matricule_pat) LEFT join medecin on (ordonnance.medecin_id=medecin.nom_utilisateur) left join utilisateurs on (medecin.nom_utilisateur=utilisateurs.nom_utilisateur) where ordonnance.ordonnance_id='" + lordonance.getText() + "'";
                JRDesignQuery updateQuery = new JRDesignQuery();
                updateQuery.setText(query);
                jdesing.setQuery(updateQuery);
                JasperReport jreport = JasperCompileManager.compileReport(jdesing);
                JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
                
                JasperViewer.viewReport(jprint);
                
            } catch (ClassNotFoundException | SQLException | JRException ex) {
                Logger.getLogger(OrdonnanceVue.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }
    }//GEN-LAST:event_bimprimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdonnanceVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdonnanceVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdonnanceVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdonnanceVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdonnanceVue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bimprimer;
    private javax.swing.JButton bquitter;
    private javax.swing.JTextField date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel limage;
    private javax.swing.JLabel lmatricule;
    private javax.swing.JLabel lnom;
    private javax.swing.JLabel lordonance;
    private javax.swing.JTextField tdosage;
    private javax.swing.JTextField tdure;
    private javax.swing.JTextField tfamille;
    private javax.swing.JTextField tforme;
    private javax.swing.JTable tmedicament;
    private javax.swing.JTextField tnommed;
    private javax.swing.JTextField tobservation;
    private javax.swing.JLabel tpath;
    private javax.swing.JTextField tposologie;
    private javax.swing.JTextField tquantite;
    // End of variables declaration//GEN-END:variables
}
