/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.ConnectUtilisateur;
import Modele.Connexion;
import static Vue.DetailsPatient.tmatricule;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.*;
import java.sql.SQLException;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author dell
 */
public class PageConsultations extends javax.swing.JInternalFrame {

    /**
     * Creates new form PagePatients
     */
    static PreparedStatement ps, stmNbConsultations;
    static DefaultTableModel model = new DefaultTableModel();
    static DefaultTableModel dft = new DefaultTableModel();
    static Connexion c = new Connexion();
    static ResultSet rs;

    public PageConsultations() {
        initComponents();
        //Pour enlever le cadre JAVA le café la.
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        //Jusqu'ici. 
        actualiserc();
    }

    public static void actualiserc() {
        tnom.setText("");
        tprenom.setText("");
        model.setRowCount(0);
        model.setColumnCount(0);
        try {
            model.addColumn("Consultation Id");
            model.addColumn("Nom du patient");
            model.addColumn("Prénom du patient");
            model.addColumn("Matricule");
            model.addColumn("Téléphone");
            model.addColumn("Diagnostique");
            model.addColumn("Résultat");
            model.addColumn("Date consultation");
            ps = c.connexionBdd().prepareStatement("SELECT * FROM patient, consultation where patient.matricule_pat = consultation.matricule_pat AND consultation.medecin_id = ?");
            ps.setString(1, authentification.tusername.getText());
            rs = ps.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("consultation_id"),
                    rs.getString("nom_pat"),
                    rs.getString("prénom_pat"),
                    rs.getString("matricule_pat"),
                    rs.getString("numTel"),
                    rs.getString("diagnostique"),
                    rs.getString("résultat_cons"),
                    rs.getString("date_cons"),}
                );
            }
            tconsultation.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(DetailsConsultationMAJ.class.getName()).log(Level.SEVERE, null, ex);
        }
        nbrconsultation.setText("                                   " + tconsultation.getRowCount());
    }

    public static void actualisero() {
        dft.setRowCount(0);
        dft.setColumnCount(0);
        try {
            dft.addColumn("ID");
            dft.addColumn("Date");
            dft.addColumn("Duré traitement");
            ps = c.connexionBdd().prepareStatement("select * from ordonnance left join consultation on (ordonnance.consultation_id=consultation.consultation_id) where consultation.consultation_id=?");

            ps.setString(1, tconsultation.getValueAt(tconsultation.getSelectedRow(), 0) + "");
            rs = ps.executeQuery();
            while (rs.next()) {
                dft.addRow(new Object[]{
                    rs.getString("ordonnance_id"),
                    rs.getString("date_or"),
                    rs.getString("duré_trait")}
                );
            }
            tordonnance.setModel(dft);
        } catch (SQLException ex) {
            Logger.getLogger(PageConsultations.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tconsultation = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nbrconsultation = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tnom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tprenom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tordonnance = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        baddor = new javax.swing.JButton();
        bmodifieror = new javax.swing.JButton();
        bmodifiercons = new javax.swing.JButton();
        bsupprimeror = new javax.swing.JButton();
        bsupprimerconc = new javax.swing.JButton();
        bactualiser = new javax.swing.JButton();
        bimprimer = new javax.swing.JButton();
        bdetailsc = new javax.swing.JButton();
        bdetailso = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1208, 792));

        jPanel14.setBackground(new java.awt.Color(137, 207, 239));
        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(89, 79, 79), 2, true));
        jPanel14.setPreferredSize(new java.awt.Dimension(1148, 705));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/acceuil(cercle).png"))); // NOI18N
        jLabel1.setText(" Consultations");
        jPanel14.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, 357, 118));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 128), 2, true));

        jPanel3.setBackground(new java.awt.Color(0, 0, 128));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Consultations");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tconsultation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tconsultation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tconsultationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tconsultation);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
        );

        jPanel14.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 289, 680, -1));

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 128), 2, true));

        jPanel5.setBackground(new java.awt.Color(0, 0, 128));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 128), 1, true));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nombre de consultations inscrits");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nbrconsultation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nbrconsultation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nbrconsultation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/patient.png"))); // NOI18N
        nbrconsultation.setText("                                   Nombre");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nbrconsultation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nbrconsultation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jPanel14.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(962, 13, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setText("Recherche ");
        jPanel14.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 121, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setText("Par nom : ");
        jPanel14.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 159, -1, -1));

        tnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnomActionPerformed(evt);
            }
        });
        jPanel14.add(tnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 159, 183, 37));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setText("Par prénom : ");
        jPanel14.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 159, -1, -1));

        tprenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tprenomActionPerformed(evt);
            }
        });
        jPanel14.add(tprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 159, 183, 37));

        jButton1.setBackground(new java.awt.Color(137, 207, 239));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 159, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tordonnance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Duré traitement"
            }
        ));
        jScrollPane2.setViewportView(tordonnance);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 540, -1));

        jPanel6.setBackground(new java.awt.Color(255, 0, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Ordonnance");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(231, 231, 231))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        jPanel14.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 283, 540, 490));

        baddor.setText("Ajouter");
        baddor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddorActionPerformed(evt);
            }
        });
        jPanel14.add(baddor, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 250, -1, -1));

        bmodifieror.setText("Modifier");
        bmodifieror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodifierorActionPerformed(evt);
            }
        });
        jPanel14.add(bmodifieror, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 250, -1, -1));

        bmodifiercons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/modifier - copie.png"))); // NOI18N
        bmodifiercons.setText("Modifier");
        bmodifiercons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodifierconsActionPerformed(evt);
            }
        });
        jPanel14.add(bmodifiercons, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        bsupprimeror.setText("Supprimer");
        bsupprimeror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsupprimerorActionPerformed(evt);
            }
        });
        jPanel14.add(bsupprimeror, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 250, -1, -1));

        bsupprimerconc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/supprimer.png"))); // NOI18N
        bsupprimerconc.setText("Supprimer");
        bsupprimerconc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsupprimerconcActionPerformed(evt);
            }
        });
        jPanel14.add(bsupprimerconc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        bactualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/acutaliser.png"))); // NOI18N
        bactualiser.setText("Actualiser");
        bactualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bactualiserActionPerformed(evt);
            }
        });
        jPanel14.add(bactualiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        bimprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imprimante_1.png"))); // NOI18N
        bimprimer.setText("Imprimer");
        bimprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bimprimerActionPerformed(evt);
            }
        });
        jPanel14.add(bimprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        bdetailsc.setText("Détails");
        bdetailsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdetailscActionPerformed(evt);
            }
        });
        jPanel14.add(bdetailsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        bdetailso.setText("Détails");
        bdetailso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdetailsoActionPerformed(evt);
            }
        });
        jPanel14.add(bdetailso, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 1275, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnomActionPerformed

    private void tprenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tprenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tprenomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tnom.getText().isEmpty() || tprenom.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez saisir le nom et le prénom !");
        } else {
            model.setRowCount(0);
            model.setColumnCount(0);
            try {
                model.addColumn("Consultation Id");
                model.addColumn("Nom du patient");
                model.addColumn("Prénom du patient");
                model.addColumn("Matricule");
                model.addColumn("Téléphone");
                model.addColumn("Diagnostique");
                model.addColumn("Résultat");
                model.addColumn("Date consultation");
                ps = c.connexionBdd().prepareStatement("SELECT * FROM patient, consultation where patient.matricule_pat = consultation.matricule_pat AND consultation.medecin_id = ? and patient.nom_pat=? and patient.prénom_pat=?");
                ps.setString(1, authentification.tusername.getText());
                ps.setString(2, tnom.getText());
                ps.setString(3, tprenom.getText());
                rs = ps.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("consultation_id"),
                        rs.getString("nom_pat"),
                        rs.getString("prénom_pat"),
                        rs.getString("matricule_pat"),
                        rs.getString("numTel"),
                        rs.getString("diagnostique"),
                        rs.getString("résultat_cons"),
                        rs.getString("date_cons"),}
                    );
                }
                tconsultation.setModel(model);
                if (model.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "pas de consultation !");
                }
            } catch (SQLException ex) {
                Logger.getLogger(DetailsConsultationMAJ.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void baddorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddorActionPerformed
        if (Médecin.prv.charAt(16) == '1') {
            ADDOrdonance ado = new ADDOrdonance();
            ado.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }
    }//GEN-LAST:event_baddorActionPerformed

    private void tconsultationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tconsultationMouseClicked
        actualisero();
    }//GEN-LAST:event_tconsultationMouseClicked

    private void bdetailscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdetailscActionPerformed
        if (Médecin.prv.charAt(32) == '1') {
            if (tconsultation.getSelectedRowCount() == 1) {
                DétailsConsultationMedVoir scmv = new DétailsConsultationMedVoir();
                scmv.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }
    }//GEN-LAST:event_bdetailscActionPerformed

    private void bmodifierconsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodifierconsActionPerformed
        if (Médecin.prv.charAt(10) == '1') {
            if (tconsultation.getSelectedRowCount() == 1) {
                DetailsConsultationMedecin dcm = new DetailsConsultationMedecin();
                dcm.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }
    }//GEN-LAST:event_bmodifierconsActionPerformed

    private void bsupprimerconcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsupprimerconcActionPerformed
        if (Médecin.prv.charAt(11) == '1') {
            if (tconsultation.getSelectedRowCount() == 1) {
                if (JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer la consultation ?", "confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    try {
                        ps = c.connexionBdd().prepareStatement("delete from consultation where consultation_id=?");
                        ps.setString(1, tconsultation.getValueAt(tconsultation.getSelectedRow(), 0) + "");
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Suppression faite avec succés");
                        actualiserc();
                    } catch (SQLException ex) {
                        Logger.getLogger(DetailsPatient.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }
    }//GEN-LAST:event_bsupprimerconcActionPerformed

    private void bactualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bactualiserActionPerformed
        actualiserc();
        dft.setRowCount(0);
        tordonnance.setModel(dft);
    }//GEN-LAST:event_bactualiserActionPerformed

    private void bimprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bimprimerActionPerformed
        if (Médecin.prv.charAt(12) == '1') {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_cabinet_medical", "root", "");
                JasperDesign jdesing = JRXmlLoader.load("C:\\Users\\azus\\Documents\\NetBeansProjects\\gestion d'une cabinet medicale V7\\src\\EtatImpression\\ListeConsultation.jrxml");
                String query = "select * from consultation where medecin_id='" + authentification.tusername.getText() + "'";
                JRDesignQuery updateQuery = new JRDesignQuery();
                updateQuery.setText(query);
                jdesing.setQuery(updateQuery);
                JasperReport jreport = JasperCompileManager.compileReport(jdesing);
                JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);

                JasperViewer.viewReport(jprint);

            } catch (ClassNotFoundException | SQLException | JRException ex) {
                Logger.getLogger(DetailsPatient.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }
    }//GEN-LAST:event_bimprimerActionPerformed

    private void bsupprimerorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsupprimerorActionPerformed
        if (Médecin.prv.charAt(18) == '1') {
            if (tordonnance.getSelectedRowCount() == 1) {
                if (JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer l'ordonnance ?", "confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    try {
                        ps = c.connexionBdd().prepareStatement("delete from ordonnance where ordonnance_id=?");
                        ps.setString(1, tordonnance.getValueAt(tordonnance.getSelectedRow(), 0) + "");
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Suppression faite avec succés");
                        actualisero();
                    } catch (SQLException ex) {
                        Logger.getLogger(DetailsPatient.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }

    }//GEN-LAST:event_bsupprimerorActionPerformed

    private void bmodifierorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodifierorActionPerformed
        if (Médecin.prv.charAt(17) == '1') {
            if (tordonnance.getSelectedRowCount() == 1) {
                OrdonnanceMAJJ adm = new OrdonnanceMAJJ();
                adm.setVisible(true);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }

    }//GEN-LAST:event_bmodifierorActionPerformed

    private void bdetailsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdetailsoActionPerformed
        if (tordonnance.getSelectedRowCount() == 1) {
            OrdonnanceVue ov = new OrdonnanceVue();
            ov.setVisible(true);
        }

    }//GEN-LAST:event_bdetailsoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bactualiser;
    private javax.swing.JButton baddor;
    private javax.swing.JButton bdetailsc;
    private javax.swing.JButton bdetailso;
    private javax.swing.JButton bimprimer;
    private javax.swing.JButton bmodifiercons;
    private javax.swing.JButton bmodifieror;
    private javax.swing.JButton bsupprimerconc;
    private javax.swing.JButton bsupprimeror;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel nbrconsultation;
    public static javax.swing.JTable tconsultation;
    public static javax.swing.JTextField tnom;
    public static javax.swing.JTable tordonnance;
    public static javax.swing.JTextField tprenom;
    // End of variables declaration//GEN-END:variables
}
