/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.ConnectPatient;
import Modele.Connexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class PageNotes extends javax.swing.JInternalFrame {

    static Connexion c = new Connexion();
    static PreparedStatement ps;
    static DefaultTableModel dft = new DefaultTableModel();
    static ResultSet rs;

    /**
     * Creates new form PageNotes
     */
    public PageNotes() {
        initComponents();

        //Pour enlever le cadre JAVA le café la.
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        //Jusqu'ici. 
        actualiser();
    }

    public static void actualiser() {
        dft.setRowCount(0);
        dft.setColumnCount(0);
        try {
            dft.addColumn("Id");
            dft.addColumn("Contenu");

            ps = c.connexionBdd().prepareStatement("select * from Notes where medecin_id=?");
            ps.setString(1, authentification.tusername.getText());
            rs = ps.executeQuery();
            while (rs.next()) {
                dft.addRow(new Object[]{
                    rs.getString("note_id"),
                    rs.getString("contenue")
                }
                );
            }
            tnotes.setModel(dft);
        } catch (SQLException ex) {
            Logger.getLogger(PageNotes.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        bdetails = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tnotes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        bmodifier = new javax.swing.JToggleButton();
        bsup = new javax.swing.JToggleButton();
        bact = new javax.swing.JToggleButton();
        bajout = new javax.swing.JToggleButton();

        jPanel14.setBackground(new java.awt.Color(137, 207, 239));
        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(89, 79, 79), 2, true));
        jPanel14.setPreferredSize(new java.awt.Dimension(1148, 705));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bdetails.setText("Détails");
        bdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdetailsActionPerformed(evt);
            }
        });
        jPanel14.add(bdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 70, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/acceuil(cercle).png"))); // NOI18N
        jLabel1.setText(" Notes");
        jPanel14.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 202, 118));

        jPanel1.setBackground(new java.awt.Color(0, 0, 128));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tnotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tnotes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 58, 1170, 380));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Les Notes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        jPanel14.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 301, 1180, 440));

        bmodifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/modifier - copie.png"))); // NOI18N
        bmodifier.setText("Modifier");
        bmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodifierActionPerformed(evt);
            }
        });
        jPanel14.add(bmodifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, -1, -1));

        bsup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/supprimer.png"))); // NOI18N
        bsup.setText("Supprimer");
        bsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsupActionPerformed(evt);
            }
        });
        jPanel14.add(bsup, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, -1, -1));

        bact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/acutaliser.png"))); // NOI18N
        bact.setText("Actualiser");
        bact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bactActionPerformed(evt);
            }
        });
        jPanel14.add(bact, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 270, -1, -1));

        bajout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus_1.png"))); // NOI18N
        bajout.setText("Ajouter");
        bajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajoutActionPerformed(evt);
            }
        });
        jPanel14.add(bajout, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 1192, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdetailsActionPerformed
        if (tnotes.getSelectedRowCount() == 1) {
            NoteVoir nv = new NoteVoir();
            nv.setVisible(true);
        }
    }//GEN-LAST:event_bdetailsActionPerformed

    private void bmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodifierActionPerformed
        if (Médecin.prv.charAt(28) == '1') {
            if (tnotes.getSelectedRowCount() == 1) {
                NoteMAJ nmaj = new NoteMAJ();
                nmaj.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }
    }//GEN-LAST:event_bmodifierActionPerformed

    private void bsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsupActionPerformed
        if (Médecin.prv.charAt(29) == '1') {
            if (tnotes.getSelectedRowCount() == 1) {
                if (JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer la note ?", "confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    try {
                        ps = c.connexionBdd().prepareStatement("delete from notes where note_id=?");
                        ps.setString(1, tnotes.getValueAt(tnotes.getSelectedRow(), 0) + "");
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Suppression faite avec succés");
                        actualiser();
                    } catch (SQLException ex) {
                        Logger.getLogger(DetailsPatient.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }
    }//GEN-LAST:event_bsupActionPerformed

    private void bactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bactActionPerformed
        actualiser();
    }//GEN-LAST:event_bactActionPerformed

    private void bajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajoutActionPerformed
       if (Médecin.prv.charAt(27) == '1') {
            ADDNotes an = new ADDNotes();
            an.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }
    }//GEN-LAST:event_bajoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bact;
    private javax.swing.JToggleButton bajout;
    private javax.swing.JToggleButton bdetails;
    private javax.swing.JToggleButton bmodifier;
    private javax.swing.JToggleButton bsup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tnotes;
    // End of variables declaration//GEN-END:variables
}
