/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.ConnectUtilisateur;
import Modele.Connexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author azus
 */
public class Paramètre extends javax.swing.JFrame {

    static Connexion c = new Connexion();
    static PreparedStatement ps, ps2;
    static DefaultTableModel dft = new DefaultTableModel();
    static ResultSet rs;
    static ConnectUtilisateur cp = new ConnectUtilisateur();

    /**
     * Creates new form Paramètre
     */
    public Paramètre() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        actualiser();
    }

    public static void actualiser() {
        dft.setRowCount(0);
        dft.setColumnCount(0);
        try {
            dft.addColumn("nom_utilisateur");
            dft.addColumn("type_utilisateur");
            dft.addColumn("mdp");
            dft.addColumn("nom");
            dft.addColumn("prénom");

            ps = c.connexionBdd().prepareStatement("select * from utilisateurs");
            rs = ps.executeQuery();
            while (rs.next()) {
                dft.addRow(new Object[]{
                    rs.getString("nom_utilisateur"),
                    rs.getString("type_utilisateur"),
                    rs.getString("mdp"),
                    rs.getString("nom"),
                    rs.getString("prénom")}
                );
            }
            tutilisateur.setModel(dft);
        } catch (SQLException ex) {
            Logger.getLogger(Paramètre.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tutilisateur = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        bsupprimer = new javax.swing.JButton();
        bactualiser = new javax.swing.JButton();
        bajouter = new javax.swing.JButton();
        bmodifier = new javax.swing.JButton();
        bquitter = new javax.swing.JButton();
        bdetails = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tutilisateur.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tutilisateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prénom", "Type", "Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(tutilisateur);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 580, 380));

        jPanel1.setBackground(new java.awt.Color(92, 173, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bsupprimer.setBackground(new java.awt.Color(204, 204, 255));
        bsupprimer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bsupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/garbage-bin (1).png"))); // NOI18N
        bsupprimer.setText("Supprimer");
        bsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsupprimerActionPerformed(evt);
            }
        });
        jPanel1.add(bsupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 130, -1));

        bactualiser.setBackground(new java.awt.Color(204, 204, 255));
        bactualiser.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bactualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/real-time (1).png"))); // NOI18N
        bactualiser.setText("Actualiser");
        bactualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bactualiserActionPerformed(evt);
            }
        });
        jPanel1.add(bactualiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        bajouter.setBackground(new java.awt.Color(204, 204, 255));
        bajouter.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ajouter-un-bouton (1) (1).png"))); // NOI18N
        bajouter.setText("Ajouter");
        bajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajouterActionPerformed(evt);
            }
        });
        jPanel1.add(bajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, -1));

        bmodifier.setBackground(new java.awt.Color(204, 204, 255));
        bmodifier.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bmodifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report (1).png"))); // NOI18N
        bmodifier.setText("Modifier");
        bmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodifierActionPerformed(evt);
            }
        });
        jPanel1.add(bmodifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, -1));

        bquitter.setBackground(new java.awt.Color(204, 204, 255));
        bquitter.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bquitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sidentifier (1) (1).png"))); // NOI18N
        bquitter.setText("Quitter");
        bquitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bquitterActionPerformed(evt);
            }
        });
        jPanel1.add(bquitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 130, -1));

        bdetails.setBackground(new java.awt.Color(204, 204, 255));
        bdetails.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/voir.png"))); // NOI18N
        bdetails.setText("Détails");
        bdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdetailsActionPerformed(evt);
            }
        });
        jPanel1.add(bdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sans titrehhhhhhhh(1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 790, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsupprimerActionPerformed
        if (tutilisateur.getSelectedRowCount() == 1) {
            if (JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer l'utisateur", "confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    ps = c.connexionBdd().prepareStatement("delete from utilisateurs where nom_utilisateur=?");
                    ps.setString(1, tutilisateur.getValueAt(tutilisateur.getSelectedRow(), 0) + "");
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "suppression faite avec succées");
                    actualiser();
                } catch (SQLException ex) {
                    Logger.getLogger(Paramètre.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_bsupprimerActionPerformed

    private void bactualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bactualiserActionPerformed
        actualiser();
    }//GEN-LAST:event_bactualiserActionPerformed

    private void bajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajouterActionPerformed
        ProfilParamètre pp = new ProfilParamètre();
        pp.setVisible(true);
    }//GEN-LAST:event_bajouterActionPerformed

    private void bmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodifierActionPerformed
        if (tutilisateur.getSelectedRowCount() == 1) {
            ProfilParamètreMAJ ppm = new ProfilParamètreMAJ();
            ppm.setVisible(true);
        }
    }//GEN-LAST:event_bmodifierActionPerformed

    private void bquitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bquitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bquitterActionPerformed

    private void bdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdetailsActionPerformed
        if (tutilisateur.getSelectedRowCount() == 1) {
            DetailsParamètre dp = new DetailsParamètre();
            dp.setVisible(true);
        }
    }//GEN-LAST:event_bdetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paramètre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paramètre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paramètre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paramètre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paramètre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bactualiser;
    private javax.swing.JButton bajouter;
    private javax.swing.JButton bdetails;
    private javax.swing.JButton bmodifier;
    private javax.swing.JButton bquitter;
    private javax.swing.JButton bsupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tutilisateur;
    // End of variables declaration//GEN-END:variables
}
