/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.*;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author azus
 */
public class ProfilePatient extends javax.swing.JFrame {

    Connexion c = new Connexion();
    PreparedStatement ps;
    DefaultTableModel dft = new DefaultTableModel();
    ResultSet rs;

    public ProfilePatient() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public String matricule() {
        String mat = null;
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        String dn = s.format(jdate.getDate());
        mat = tnom.getText().substring(0, 3) + tprenom.getText().substring(0, 3) + dn.substring(8) + (AcceuilSecretaire.tpatient.getRowCount() + 1);
        return mat.toUpperCase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpath = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tnom = new javax.swing.JTextField();
        tprenom = new javax.swing.JTextField();
        tmaladie = new javax.swing.JTextField();
        jdate = new com.toedter.calendar.JDateChooser();
        csanguin = new javax.swing.JComboBox<>();
        csexe = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        csituationfamiliale = new javax.swing.JComboBox<>();
        ttel = new javax.swing.JTextField();
        ttelurgence = new javax.swing.JTextField();
        tnumsecurite = new javax.swing.JTextField();
        temail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tadresse = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tnote = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tantpersonnels = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        tantfamiliaux = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        tantmedicaux = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        tantchirurgicaux = new javax.swing.JTextArea();
        bimprimer = new javax.swing.JButton();
        bannuler = new javax.swing.JButton();
        bajouter = new javax.swing.JButton();
        tmatricule = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        limage = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lfond = new javax.swing.JLabel();

        tpath.setEditable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Nom * :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("prénom * :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Date de naissance * :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Maladie * :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("N° tél * :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Adresse * :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Antécédents personnels :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Antécédents familiaux :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Antécédents médicaux :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Groupe sanguin * :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Sexe * :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("N° sécurité social * :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Note :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("émail  :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Matricule :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("N° tél cas d'urgence * :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Antécédents chirurgicaux");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, -1, -1));

        tnom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tnom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tnomFocusLost(evt);
            }
        });
        tnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnomActionPerformed(evt);
            }
        });
        getContentPane().add(tnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 200, -1));

        tprenom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tprenom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tprenomFocusLost(evt);
            }
        });
        getContentPane().add(tprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 200, -1));

        tmaladie.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tmaladie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tmaladieFocusGained(evt);
            }
        });
        getContentPane().add(tmaladie, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 200, -1));

        jdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdateFocusLost(evt);
            }
        });
        getContentPane().add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 200, -1));

        csanguin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        csanguin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));
        getContentPane().add(csanguin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 200, -1));

        csexe.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        csexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Féminin", "Masculin" }));
        getContentPane().add(csexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 200, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Situation familial * :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, -1, -1));

        csituationfamiliale.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        csituationfamiliale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Célibataire", "Marié/e", "Veuf/Veuve" }));
        getContentPane().add(csituationfamiliale, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 200, -1));

        ttel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(ttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 300, -1));

        ttelurgence.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(ttelurgence, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 300, -1));

        tnumsecurite.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(tnumsecurite, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 300, -1));

        temail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 300, -1));

        tadresse.setColumns(20);
        tadresse.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tadresse.setRows(5);
        jScrollPane1.setViewportView(tadresse);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 300, 120));

        tnote.setColumns(20);
        tnote.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tnote.setRows(5);
        jScrollPane2.setViewportView(tnote);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 300, 120));

        tantpersonnels.setColumns(20);
        tantpersonnels.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tantpersonnels.setRows(5);
        jScrollPane3.setViewportView(tantpersonnels);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 550, 320, -1));

        tantfamiliaux.setColumns(20);
        tantfamiliaux.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tantfamiliaux.setRows(5);
        jScrollPane4.setViewportView(tantfamiliaux);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 320, -1));

        tantmedicaux.setColumns(20);
        tantmedicaux.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tantmedicaux.setRows(5);
        jScrollPane5.setViewportView(tantmedicaux);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 320, -1));

        tantchirurgicaux.setColumns(20);
        tantchirurgicaux.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tantchirurgicaux.setRows(5);
        jScrollPane6.setViewportView(tantchirurgicaux);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 320, -1));

        bimprimer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bimprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imprimante.png"))); // NOI18N
        bimprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bimprimerActionPerformed(evt);
            }
        });
        getContentPane().add(bimprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 650, -1, -1));

        bannuler.setBackground(new java.awt.Color(255, 0, 0));
        bannuler.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bannuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/croix.png"))); // NOI18N
        bannuler.setText("Annuler");
        bannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bannulerActionPerformed(evt);
            }
        });
        getContentPane().add(bannuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 650, -1, -1));

        bajouter.setBackground(new java.awt.Color(0, 204, 204));
        bajouter.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/verifier.png"))); // NOI18N
        bajouter.setText("Valider");
        bajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajouterActionPerformed(evt);
            }
        });
        getContentPane().add(bajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 650, 100, -1));

        tmatricule.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        getContentPane().add(tmatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 200, 20));

        jPanel2.setBackground(new java.awt.Color(227, 226, 226));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        limage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limageMouseClicked(evt);
            }
        });
        jPanel1.add(limage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 60));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 50, 60));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setText("Fiche patient :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FichePatient.png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        lfond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Coordonnées Patient (1).png"))); // NOI18N
        getContentPane().add(lfond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bannulerActionPerformed
        dispose();
    }//GEN-LAST:event_bannulerActionPerformed

    private void bimprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bimprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bimprimerActionPerformed

    private void tnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnomActionPerformed

    private void tnomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tnomFocusLost
        if (!tnom.getText().isEmpty()) {
            tnom.setText(tnom.getText().toUpperCase());
        }
    }//GEN-LAST:event_tnomFocusLost

    private void tprenomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tprenomFocusLost
        if (!tprenom.getText().isEmpty()) {
            tprenom.setText(tprenom.getText().substring(0, 1).toUpperCase() + tprenom.getText().substring(1).toLowerCase());
        }
    }//GEN-LAST:event_tprenomFocusLost

    private void bajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajouterActionPerformed
        if ( tnom.getText().isEmpty() || tprenom.getText().isEmpty()|| tnumsecurite.getText().isEmpty()
                || jdate.getDate() == null || tmaladie.getText().isEmpty()
                || ttel.getText().isEmpty() || ttelurgence.getText().isEmpty() || tadresse.getText().isEmpty() || tpath.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez Renseigner tout les champs !!");
        } else {
            try {
                tmatricule.setText(matricule());
                ps = c.connexionBdd().prepareStatement("insert into patient(matricule_pat,nom_pat,prénom_pat,date_naissance,maladie_pat,numTel,numTelUrgence,adresse_pat,antécédents_personnels,antécédents_familiaux,antécédents_médicaux,antécédents_chirurgicaux,groupe_sanguin,sexe,num_sécurité_social,photo_patient,email,note,situation_familiale,tpath) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                ps.setString(1, tmatricule.getText());
                ps.setString(2, tnom.getText());
                ps.setString(3, tprenom.getText());
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String daten = sdf.format(jdate.getDate());
                ps.setString(4, daten);
                ps.setString(5, tmaladie.getText());
                ps.setString(6, ttel.getText());
                ps.setString(7, ttelurgence.getText());
                ps.setString(8, tadresse.getText());
                ps.setString(9, tantpersonnels.getText());
                ps.setString(10, tantfamiliaux.getText());
                ps.setString(11, tantmedicaux.getText());
                ps.setString(12, tantchirurgicaux.getText());
                ps.setString(13, csanguin.getSelectedItem() + "");
                ps.setString(14, csexe.getSelectedItem() + "");
                ps.setString(15, tnumsecurite.getText());
                try {
                    InputStream is = new FileInputStream(tpath.getText());
                    ps.setBlob(16, is);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ProfilePatient.class.getName()).log(Level.SEVERE, null, ex);
                }
                ps.setString(17, temail.getText());
                ps.setString(18, tnote.getText());
                ps.setString(19, csituationfamiliale.getSelectedItem() + "");
                ps.setString(20, tpath.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "le patient a été ajouter avec succés");
                AcceuilSecretaire.actualiser();
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(ProfilePatient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_bajouterActionPerformed

    private void jdateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdateFocusLost

    }//GEN-LAST:event_jdateFocusLost

    private void tmaladieFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tmaladieFocusGained
        
    }//GEN-LAST:event_tmaladieFocusGained
    String str;
    private void limageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limageMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("C:\\Users\\azus\\Desktop\\RESSOURCES ADMIN\\Table avec images\\PHOTOS STAGIAIRES"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image", "jpg", "png", "gif");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File fichierselectionne = fileChooser.getSelectedFile();
            String path = fichierselectionne.getAbsolutePath();
            ImageIcon img = new ImageIcon(path);
            Image imgrec = img.getImage();
            Image nimage = imgrec.getScaledInstance(limage.getWidth(),
                    limage.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon imgfinal = new ImageIcon(nimage);
            limage.setIcon(imgfinal);
            str = path;
            tpath.setText(str);
        } else if (result == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null, "Aucun choix effectué");
        }
    }//GEN-LAST:event_limageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfilePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfilePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfilePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfilePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfilePatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bajouter;
    private javax.swing.JButton bannuler;
    private javax.swing.JButton bimprimer;
    private javax.swing.JComboBox<String> csanguin;
    private javax.swing.JComboBox<String> csexe;
    private javax.swing.JComboBox<String> csituationfamiliale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JLabel lfond;
    private javax.swing.JLabel limage;
    private javax.swing.JTextArea tadresse;
    private javax.swing.JTextArea tantchirurgicaux;
    private javax.swing.JTextArea tantfamiliaux;
    private javax.swing.JTextArea tantmedicaux;
    private javax.swing.JTextArea tantpersonnels;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tmaladie;
    private javax.swing.JLabel tmatricule;
    private javax.swing.JTextField tnom;
    private javax.swing.JTextArea tnote;
    private javax.swing.JTextField tnumsecurite;
    private javax.swing.JTextField tpath;
    private javax.swing.JTextField tprenom;
    private javax.swing.JTextField ttel;
    private javax.swing.JTextField ttelurgence;
    // End of variables declaration//GEN-END:variables
}
