/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author azus
 */
public class ProfilParamètre extends javax.swing.JFrame {

    Connexion c = new Connexion();
    PreparedStatement ps, ps2;
    DefaultTableModel dft = new DefaultTableModel();
    ResultSet rs;

    /**
     * Creates new form ProfilParamètre
     */
    public ProfilParamètre() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tusername = new javax.swing.JTextField();
        tprenom = new javax.swing.JTextField();
        tnom = new javax.swing.JTextField();
        ctype = new javax.swing.JComboBox<>();
        tspecialite = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tpassword = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        caddpatient = new javax.swing.JCheckBox();
        cdetailspatient = new javax.swing.JCheckBox();
        cmodifierpatient = new javax.swing.JCheckBox();
        cdelpatient = new javax.swing.JCheckBox();
        cmodifierconsultation = new javax.swing.JCheckBox();
        cdelconsultation = new javax.swing.JCheckBox();
        caddconsultation = new javax.swing.JCheckBox();
        caddrdv = new javax.swing.JCheckBox();
        cdelrdv = new javax.swing.JCheckBox();
        cmodifierrdv = new javax.swing.JCheckBox();
        cimprimerfac = new javax.swing.JCheckBox();
        caddrevenue = new javax.swing.JCheckBox();
        creglerfacture = new javax.swing.JCheckBox();
        cmodifierdepense = new javax.swing.JCheckBox();
        cdeldepense = new javax.swing.JCheckBox();
        cadddepense = new javax.swing.JCheckBox();
        cdelrevenue = new javax.swing.JCheckBox();
        cmodifierrevenue = new javax.swing.JCheckBox();
        cdelordonance = new javax.swing.JCheckBox();
        caddordonance = new javax.swing.JCheckBox();
        cmodifierordonance = new javax.swing.JCheckBox();
        cdelsalleattente = new javax.swing.JCheckBox();
        cimprimerfichepatient = new javax.swing.JCheckBox();
        caddsalleattente = new javax.swing.JCheckBox();
        cdelnote = new javax.swing.JCheckBox();
        caddnote = new javax.swing.JCheckBox();
        cmodifiernote = new javax.swing.JCheckBox();
        cimprimerlistedep = new javax.swing.JCheckBox();
        cimprimerconsultation = new javax.swing.JCheckBox();
        cimprimerrevenue = new javax.swing.JCheckBox();
        cimprimerordonance = new javax.swing.JCheckBox();
        csalleattente = new javax.swing.JCheckBox();
        cdetailsrdv = new javax.swing.JCheckBox();
        cdetailsconsultation = new javax.swing.JCheckBox();
        cdetailsordonance = new javax.swing.JCheckBox();
        bannuler = new javax.swing.JButton();
        bajouter = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Username * :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Prénom * :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Password * :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Type * :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Nom * :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        tusername.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tusernameFocusLost(evt);
            }
        });
        getContentPane().add(tusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 130, -1));

        tprenom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(tprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 140, -1));

        tnom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tnom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tnomFocusLost(evt);
            }
        });
        tnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnomActionPerformed(evt);
            }
        });
        getContentPane().add(tnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 140, -1));

        ctype.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ctype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Secrétaire", "Médecin", "Comptable" }));
        ctype.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ctypeFocusLost(evt);
            }
        });
        ctype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctypeActionPerformed(evt);
            }
        });
        getContentPane().add(ctype, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 150, 30));

        tspecialite.setEditable(false);
        tspecialite.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tspecialite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tspecialiteActionPerformed(evt);
            }
        });
        getContentPane().add(tspecialite, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 150, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("spécialité :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        tpassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(tpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 130, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/utilisateur (1).png"))); // NOI18N
        jLabel8.setText("Fiche Utilisateur");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Droits d'utilisateur", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        caddpatient.setBackground(new java.awt.Color(255, 255, 255));
        caddpatient.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        caddpatient.setText("Ajouter Patient");
        jPanel1.add(caddpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        cdetailspatient.setBackground(new java.awt.Color(255, 255, 255));
        cdetailspatient.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cdetailspatient.setText("Détails patient");
        jPanel1.add(cdetailspatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        cmodifierpatient.setBackground(new java.awt.Color(255, 255, 255));
        cmodifierpatient.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmodifierpatient.setText("Modifier Patient");
        cmodifierpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmodifierpatientActionPerformed(evt);
            }
        });
        jPanel1.add(cmodifierpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        cdelpatient.setBackground(new java.awt.Color(255, 255, 255));
        cdelpatient.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cdelpatient.setText("Supprimer Patient");
        jPanel1.add(cdelpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        cmodifierconsultation.setBackground(new java.awt.Color(255, 255, 255));
        cmodifierconsultation.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmodifierconsultation.setText("Modifier Consultation");
        jPanel1.add(cmodifierconsultation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        cdelconsultation.setBackground(new java.awt.Color(255, 255, 255));
        cdelconsultation.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cdelconsultation.setText("Supprimer Consultation");
        jPanel1.add(cdelconsultation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        caddconsultation.setBackground(new java.awt.Color(255, 255, 255));
        caddconsultation.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        caddconsultation.setText("Ajouter Consultation");
        jPanel1.add(caddconsultation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        caddrdv.setBackground(new java.awt.Color(255, 255, 255));
        caddrdv.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        caddrdv.setText("Ajouter Rendez-vous");
        caddrdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caddrdvActionPerformed(evt);
            }
        });
        jPanel1.add(caddrdv, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        cdelrdv.setBackground(new java.awt.Color(255, 255, 255));
        cdelrdv.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cdelrdv.setText("Supprimer Rendez-vous");
        jPanel1.add(cdelrdv, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        cmodifierrdv.setBackground(new java.awt.Color(255, 255, 255));
        cmodifierrdv.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmodifierrdv.setText("Modifier Rendez-vous");
        jPanel1.add(cmodifierrdv, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        cimprimerfac.setBackground(new java.awt.Color(255, 255, 255));
        cimprimerfac.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cimprimerfac.setText("Imprimer facture");
        jPanel1.add(cimprimerfac, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, -1, -1));

        caddrevenue.setBackground(new java.awt.Color(255, 255, 255));
        caddrevenue.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        caddrevenue.setText("Ajouter Revenue");
        jPanel1.add(caddrevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        creglerfacture.setBackground(new java.awt.Color(255, 255, 255));
        creglerfacture.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        creglerfacture.setText("Régler facture");
        jPanel1.add(creglerfacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, -1, -1));

        cmodifierdepense.setBackground(new java.awt.Color(255, 255, 255));
        cmodifierdepense.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmodifierdepense.setText("Modifier dépense");
        cmodifierdepense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmodifierdepenseActionPerformed(evt);
            }
        });
        jPanel1.add(cmodifierdepense, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        cdeldepense.setBackground(new java.awt.Color(255, 255, 255));
        cdeldepense.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cdeldepense.setText("Supprimer dépense");
        jPanel1.add(cdeldepense, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        cadddepense.setBackground(new java.awt.Color(255, 255, 255));
        cadddepense.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cadddepense.setText("Ajouter Dépense");
        jPanel1.add(cadddepense, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        cdelrevenue.setBackground(new java.awt.Color(255, 255, 255));
        cdelrevenue.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cdelrevenue.setText("Supprimer Revenue");
        jPanel1.add(cdelrevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        cmodifierrevenue.setBackground(new java.awt.Color(255, 255, 255));
        cmodifierrevenue.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmodifierrevenue.setText("Modifier Revenue");
        jPanel1.add(cmodifierrevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        cdelordonance.setBackground(new java.awt.Color(255, 255, 255));
        cdelordonance.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cdelordonance.setText("Supprimer Ordonance");
        jPanel1.add(cdelordonance, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        caddordonance.setBackground(new java.awt.Color(255, 255, 255));
        caddordonance.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        caddordonance.setText("Ajouter Ordonance");
        jPanel1.add(caddordonance, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        cmodifierordonance.setBackground(new java.awt.Color(255, 255, 255));
        cmodifierordonance.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmodifierordonance.setText("Modifier Ordonance");
        jPanel1.add(cmodifierordonance, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        cdelsalleattente.setBackground(new java.awt.Color(255, 255, 255));
        cdelsalleattente.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cdelsalleattente.setText("Supprimer de salle d'attente");
        cdelsalleattente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdelsalleattenteActionPerformed(evt);
            }
        });
        jPanel1.add(cdelsalleattente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        cimprimerfichepatient.setBackground(new java.awt.Color(255, 255, 255));
        cimprimerfichepatient.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cimprimerfichepatient.setText("Imprimer Fiche patient");
        cimprimerfichepatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cimprimerfichepatientActionPerformed(evt);
            }
        });
        jPanel1.add(cimprimerfichepatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        caddsalleattente.setBackground(new java.awt.Color(255, 255, 255));
        caddsalleattente.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        caddsalleattente.setText("Ajouter Salle d'attente");
        jPanel1.add(caddsalleattente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        cdelnote.setBackground(new java.awt.Color(255, 255, 255));
        cdelnote.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cdelnote.setText("Supprimer Note");
        jPanel1.add(cdelnote, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        caddnote.setBackground(new java.awt.Color(255, 255, 255));
        caddnote.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        caddnote.setText("Ajouter Note");
        caddnote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caddnoteActionPerformed(evt);
            }
        });
        jPanel1.add(caddnote, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        cmodifiernote.setBackground(new java.awt.Color(255, 255, 255));
        cmodifiernote.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmodifiernote.setText("Modifier Note");
        jPanel1.add(cmodifiernote, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        cimprimerlistedep.setBackground(new java.awt.Color(255, 255, 255));
        cimprimerlistedep.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cimprimerlistedep.setText("Imprimer liste Dépense");
        cimprimerlistedep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cimprimerlistedepActionPerformed(evt);
            }
        });
        jPanel1.add(cimprimerlistedep, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        cimprimerconsultation.setBackground(new java.awt.Color(255, 255, 255));
        cimprimerconsultation.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cimprimerconsultation.setText("Imprimer liste consultation");
        cimprimerconsultation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cimprimerconsultationActionPerformed(evt);
            }
        });
        jPanel1.add(cimprimerconsultation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        cimprimerrevenue.setBackground(new java.awt.Color(255, 255, 255));
        cimprimerrevenue.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cimprimerrevenue.setText("Imprimer liste Revenues");
        cimprimerrevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cimprimerrevenueActionPerformed(evt);
            }
        });
        jPanel1.add(cimprimerrevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        cimprimerordonance.setBackground(new java.awt.Color(255, 255, 255));
        cimprimerordonance.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cimprimerordonance.setText("Imprimer Ordonance");
        jPanel1.add(cimprimerordonance, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        csalleattente.setBackground(new java.awt.Color(255, 255, 255));
        csalleattente.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        csalleattente.setText("Fenêtre Salle d'attente");
        csalleattente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csalleattenteActionPerformed(evt);
            }
        });
        jPanel1.add(csalleattente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        cdetailsrdv.setBackground(new java.awt.Color(255, 255, 255));
        cdetailsrdv.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cdetailsrdv.setText("Détails Rendez-vous");
        jPanel1.add(cdetailsrdv, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        cdetailsconsultation.setBackground(new java.awt.Color(255, 255, 255));
        cdetailsconsultation.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cdetailsconsultation.setText("Détails consultation");
        jPanel1.add(cdetailsconsultation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        cdetailsordonance.setBackground(new java.awt.Color(255, 255, 255));
        cdetailsordonance.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cdetailsordonance.setText("Détails Ordonance");
        jPanel1.add(cdetailsordonance, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 750, 350));

        bannuler.setBackground(new java.awt.Color(204, 204, 255));
        bannuler.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bannuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bouton-croix (1).png"))); // NOI18N
        bannuler.setText("Quitter");
        bannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bannulerActionPerformed(evt);
            }
        });
        getContentPane().add(bannuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, -1, 40));

        bajouter.setBackground(new java.awt.Color(204, 204, 255));
        bajouter.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check-mark (1).png"))); // NOI18N
        bajouter.setText("Valider");
        bajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajouterActionPerformed(evt);
            }
        });
        getContentPane().add(bajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, -1, 40));

        jLabel7.setBackground(new java.awt.Color(0, 204, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sans titrehhhhhhhh(1).jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 810, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnomActionPerformed

    private void ctypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctypeActionPerformed

    }//GEN-LAST:event_ctypeActionPerformed

    private void tspecialiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tspecialiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tspecialiteActionPerformed

    private void ctypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ctypeFocusLost
        if (ctype.getSelectedItem().equals("Médecin")) {
            tspecialite.setEditable(true);
        } else {
            tspecialite.setText("");
            tspecialite.setEditable(false);
        }
    }//GEN-LAST:event_ctypeFocusLost

    private void tnomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tnomFocusLost

    }//GEN-LAST:event_tnomFocusLost

    private void tusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tusernameFocusLost
        boolean tr = false;
        ConnectUtilisateur cu = new ConnectUtilisateur();
        try {
            while (cu.rs.next()) {
                if ((tusername.getText().equals(cu.rs.getString("nom_utilisateur")))) {
                    tr = true;
                    break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProfilParamètre.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(tr==true){
            JOptionPane.showMessageDialog(this, "Le username dois être unique");
            tusername.setText("");
        }

    }//GEN-LAST:event_tusernameFocusLost

    private void cmodifierpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmodifierpatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmodifierpatientActionPerformed

    private void caddrdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caddrdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caddrdvActionPerformed

    private void cmodifierdepenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmodifierdepenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmodifierdepenseActionPerformed

    private void cdelsalleattenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdelsalleattenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdelsalleattenteActionPerformed

    private void cimprimerfichepatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cimprimerfichepatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cimprimerfichepatientActionPerformed

    private void caddnoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caddnoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caddnoteActionPerformed

    private void cimprimerlistedepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cimprimerlistedepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cimprimerlistedepActionPerformed

    private void cimprimerconsultationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cimprimerconsultationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cimprimerconsultationActionPerformed

    private void cimprimerrevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cimprimerrevenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cimprimerrevenueActionPerformed

    private void csalleattenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csalleattenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csalleattenteActionPerformed

    private void bannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bannulerActionPerformed
        dispose();
    }//GEN-LAST:event_bannulerActionPerformed

    private void bajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajouterActionPerformed
        String privilege = "";
        if (ctype.getSelectedItem().equals("Admin")) {
            privilege = "11111111111111111111111111111111111";
        } else {
            if (caddpatient.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cmodifierpatient.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cdelpatient.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cdetailspatient.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cimprimerfichepatient.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cadddepense.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cmodifierdepense.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cdeldepense.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cimprimerlistedep.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (caddconsultation.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cmodifierconsultation.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cdelconsultation.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cimprimerconsultation.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (caddrdv.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cmodifierrdv.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cdelrdv.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (caddordonance.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cmodifierordonance.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cdelordonance.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cimprimerordonance.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (caddsalleattente.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cdelsalleattente.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (csalleattente.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (caddrevenue.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cmodifierrevenue.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cdelrevenue.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cimprimerrevenue.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (caddnote.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cmodifiernote.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cdelnote.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (creglerfacture.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cimprimerfac.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cdetailsconsultation.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cdetailsordonance.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }
            if (cdetailsrdv.isSelected()) {
                privilege = privilege + "1";
            } else {
                privilege = privilege + "0";
            }

        }
        if (tnom.getText().isEmpty() || tpassword.getText().isEmpty() || tprenom.getText().isEmpty()
            || tusername.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez Renseigner tout les champs !!");
        } else {
            try {
                ps = c.connexionBdd().prepareStatement("insert into utilisateurs(nom_utilisateur,type_utilisateur,mdp,nom,prénom,privilége) values(?,?,?,?,?,?)");
                ps.setString(1, tusername.getText());
                ps.setString(2, ctype.getSelectedItem() + "");
                ps.setString(3, tpassword.getText());
                ps.setString(4, tnom.getText());
                ps.setString(5, tprenom.getText());
                ps.setString(6, privilege);
                ps.execute();
                if (ctype.getSelectedItem().equals("Médecin")) {
                    ps2 = c.connexionBdd().prepareStatement("update medecin set specialite=? where nom_utilisateur=? ");
                    ps2.setString(1, tusername.getText());
                    ps2.setString(2, tspecialite.getText());
                    ps2.execute();
                }
                JOptionPane.showMessageDialog(this, "l'utilisateur a été ajouter avec succées");
                Paramètre.actualiser();
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(ProfilParamètre.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bajouterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfilParamètre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfilParamètre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfilParamètre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfilParamètre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfilParamètre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bajouter;
    private javax.swing.JButton bannuler;
    private javax.swing.JCheckBox caddconsultation;
    private javax.swing.JCheckBox cadddepense;
    private javax.swing.JCheckBox caddnote;
    private javax.swing.JCheckBox caddordonance;
    private javax.swing.JCheckBox caddpatient;
    private javax.swing.JCheckBox caddrdv;
    private javax.swing.JCheckBox caddrevenue;
    private javax.swing.JCheckBox caddsalleattente;
    private javax.swing.JCheckBox cdelconsultation;
    private javax.swing.JCheckBox cdeldepense;
    private javax.swing.JCheckBox cdelnote;
    private javax.swing.JCheckBox cdelordonance;
    private javax.swing.JCheckBox cdelpatient;
    private javax.swing.JCheckBox cdelrdv;
    private javax.swing.JCheckBox cdelrevenue;
    private javax.swing.JCheckBox cdelsalleattente;
    private javax.swing.JCheckBox cdetailsconsultation;
    private javax.swing.JCheckBox cdetailsordonance;
    private javax.swing.JCheckBox cdetailspatient;
    private javax.swing.JCheckBox cdetailsrdv;
    private javax.swing.JCheckBox cimprimerconsultation;
    private javax.swing.JCheckBox cimprimerfac;
    private javax.swing.JCheckBox cimprimerfichepatient;
    private javax.swing.JCheckBox cimprimerlistedep;
    private javax.swing.JCheckBox cimprimerordonance;
    private javax.swing.JCheckBox cimprimerrevenue;
    private javax.swing.JCheckBox cmodifierconsultation;
    private javax.swing.JCheckBox cmodifierdepense;
    private javax.swing.JCheckBox cmodifiernote;
    private javax.swing.JCheckBox cmodifierordonance;
    private javax.swing.JCheckBox cmodifierpatient;
    private javax.swing.JCheckBox cmodifierrdv;
    private javax.swing.JCheckBox cmodifierrevenue;
    private javax.swing.JCheckBox creglerfacture;
    private javax.swing.JCheckBox csalleattente;
    private javax.swing.JComboBox<String> ctype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tnom;
    private javax.swing.JTextField tpassword;
    private javax.swing.JTextField tprenom;
    private javax.swing.JTextField tspecialite;
    private javax.swing.JTextField tusername;
    // End of variables declaration//GEN-END:variables
}
