/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.Connexion;
import static Vue.AcceuilSecretaire.dft;
import static Vue.AcceuilSecretaire.prv;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author azus
 */
public class SalleAttente extends javax.swing.JFrame {

    /**
     * Creates new form SalleAttente
     */
    Connexion c = new Connexion();
    PreparedStatement ps;
    DefaultTableModel dft = new DefaultTableModel();
    ResultSet rs;

    public SalleAttente() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        actualiser();
    }

    public void actualiser() {
        dft.setRowCount(0);
        dft.setColumnCount(0);
        try {
            dft.addColumn("Matricule");
            dft.addColumn("Nom");
            dft.addColumn("Prénom");
            dft.addColumn("Né(e) le");
            dft.addColumn("N°Tél");
            dft.addColumn("Adresse");
            dft.addColumn("Sexe");
            dft.addColumn("Maladie");
            dft.addColumn("état");

            ps = c.connexionBdd().prepareStatement("select patient.* from patient,salle_attente where patient.matricule_pat=salle_attente.matricule_pat");
            rs = ps.executeQuery();
            while (rs.next()) {
                dft.addRow(new Object[]{
                    rs.getString("matricule_pat"),
                    rs.getString("nom_pat"),
                    rs.getString("prénom_pat"),
                    rs.getString("date_naissance"),
                    rs.getString("numTel"),
                    rs.getString("adresse_pat"),
                    rs.getString("sexe"),
                    rs.getString("maladie_pat"),
                    "Attente"
                }
                );
            }
            tpatientatt.setModel(dft);
        } catch (SQLException ex) {
            Logger.getLogger(SalleAttente.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tpatientatt = new javax.swing.JTable();
        bsupprimer = new javax.swing.JButton();
        bquitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tpatientatt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricule", "Nom", "Prénom", "Né(e) le ", "N° Téléphone", "Adresse", "Sexe", "Etat"
            }
        ));
        jScrollPane1.setViewportView(tpatientatt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 820, 300));

        bsupprimer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bsupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/supprimer-le-symbole.png"))); // NOI18N
        bsupprimer.setText("Supprimer");
        bsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(bsupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 400, 130, -1));

        bquitter.setBackground(new java.awt.Color(255, 0, 0));
        bquitter.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bquitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/croix.png"))); // NOI18N
        bquitter.setText("Quitter");
        bquitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bquitterActionPerformed(evt);
            }
        });
        getContentPane().add(bquitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bquitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bquitterActionPerformed
        dispose();
    }//GEN-LAST:event_bquitterActionPerformed

    private void bsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsupprimerActionPerformed
        if (prv.charAt(21) == '1') {
            if (tpatientatt.getSelectedRowCount() == 1) {
                if (JOptionPane.showConfirmDialog(this, "La consultation est terminé ??", "confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    try {
                        ps = c.connexionBdd().prepareStatement("delete from salle_attente where matricule_pat=?");
                        ps.setString(1, tpatientatt.getValueAt(tpatientatt.getSelectedRow(), 0) + "");
                        ps.executeUpdate();
                        actualiser();
                    } catch (SQLException ex) {
                        Logger.getLogger(AcceuilSecretaire.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vous disposer pas de ce privilége !");
        }
    }//GEN-LAST:event_bsupprimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalleAttente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalleAttente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalleAttente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalleAttente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalleAttente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bquitter;
    private javax.swing.JButton bsupprimer;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tpatientatt;
    // End of variables declaration//GEN-END:variables
}
