/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author azus
 */
public class ValiderPayement extends javax.swing.JFrame {

    /**
     * Creates new form ValiderPayement
     */
    Connexion c = new Connexion();
    PreparedStatement ps;
    DefaultTableModel dft = new DefaultTableModel();
    ResultSet rs;

    public ValiderPayement() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tmontantverse = new javax.swing.JTextField();
        jdate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdescription = new javax.swing.JTextArea();
        bannuler = new javax.swing.JButton();
        bvalider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Date versement * :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Montant versé * :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("description de versement :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        tmontantverse.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tmontantverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmontantverseActionPerformed(evt);
            }
        });
        getContentPane().add(tmontantverse, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 180, -1));
        getContentPane().add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 190, -1));

        tdescription.setColumns(20);
        tdescription.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tdescription.setRows(5);
        jScrollPane1.setViewportView(tdescription);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        bannuler.setBackground(new java.awt.Color(255, 0, 0));
        bannuler.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bannuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/croix.png"))); // NOI18N
        bannuler.setText("Annuler");
        bannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bannulerActionPerformed(evt);
            }
        });
        getContentPane().add(bannuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        bvalider.setBackground(new java.awt.Color(0, 204, 204));
        bvalider.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bvalider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/verifier.png"))); // NOI18N
        bvalider.setText("Valider");
        bvalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bvaliderActionPerformed(evt);
            }
        });
        getContentPane().add(bvalider, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tmontantverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmontantverseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmontantverseActionPerformed

    private void bannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bannulerActionPerformed
        dispose();
    }//GEN-LAST:event_bannulerActionPerformed

    private void bvaliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bvaliderActionPerformed
        if (tmontantverse.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez Renseigner tout les champs !!");
        } else {
            try {
                float mv = Float.parseFloat(tmontantverse.getText());
                float m = 0;
                ps = c.connexionBdd().prepareStatement("select montant from facture where facture_id=?");
                ps.setString(1, DetailsPatient.tfacture.getValueAt(DetailsPatient.tfacture.getSelectedRow(), 0) + "");
                rs = ps.executeQuery();
                while (rs.next()) {
                    m = rs.getFloat("montant");
                }
                ps = c.connexionBdd().prepareStatement("update facture set date_versement=? ,montant_versé=? , reste=?, descriprion_versement=? where facture_id=?");
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String daten = sdf.format(jdate.getDate());
                ps.setString(1, daten);
                ps.setString(2, tmontantverse.getText());
                ps.setFloat(3, m - mv);
                ps.setString(4, tdescription.getText());

                ps.setString(5, DetailsPatient.tfacture.getValueAt(DetailsPatient.tfacture.getSelectedRow(), 0) + "");
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Paiement valider avec succés");
                DetailsPatient.actualiserfac();
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(ValiderPayement.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bvaliderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValiderPayement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValiderPayement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValiderPayement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValiderPayement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValiderPayement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bannuler;
    private javax.swing.JButton bvalider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JTextArea tdescription;
    private javax.swing.JTextField tmontantverse;
    // End of variables declaration//GEN-END:variables
}
